### ISSUE TITLE
How to i write pako.deflate after data?

### ISSUE THREAD

**Issue by demoonGame** [nodeca/pako#100]
I want write deflate date

So i make like this.
```
fs.readFile("text.json",(err,data)=>{
    var binaryString = pako.deflate(JSON.stringify(data), { to: 'string' });
        fs.writeFileSync("pako(press).pako",binaryString,(err)=>{
    console.log('done');
})
})
```

But not working
`
TypeError: Expected options to be either an object or a string, but got function instead
    at throwOptionsError (fs.js:81:9)
    at Object.fs.writeFileSync (fs.js:1326:5)
    at fs.readFile (D:\develop\piforwatch\router\crawler.js:52:12)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)`

make under code and turn off my node server.

How to i write pako.deflate data?

**Comment by puzrin** [comment]
`.writeFileSync()` needs buffer or utf8 string.

1. remove `{ to: 'string' }`.
2. If does not help, force cast to buffer: `Buffer.from(result)`

Also, read https://github.com/nodeca/pako/tree/master/examples
