### ISSUE TITLE
gzip operation generates corrupted compression data on safari. it works perfectly well on firefox, chrome and IE

### ISSUE THREAD

**Issue by adnomus** [nodeca/pako#101]
var send_message=function(message) {
  var request=JSON.parse(message);
  var request_url=request[0];
  var request_message=request[1];

  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      console.log(this.responseText);
    }
  };

  if(request_message!=null) {
    xhttp.open("POST", request_url, true);
    xhttp.setRequestHeader('Content-Encoding', 'gzip');
    request_message=pako.gzip(request_message,{level:9});
    xhttp.send(request_message);
  }
  else {
    xhttp.open("GET", request_url, true);
    xhttp.send();
  }

}

**Comment by puzrin** [comment]
That's not related to this package anyhow. Your code is about XMLHttpRequest.

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/tree/master/test/browser you can open this test in your browser to check.

**Comment by adnomus** [comment]
I believe that for some reason gzip call generates a corrupted package on safari. the reason I included the XMLHttpRequest code is because I wanted to share the use case. This example works perfectly correct on the other browsers.

**Comment by puzrin** [comment]
If you believe that bug is in this package - please, provide a minimal possible sample, related to this package only.
