### ISSUE TITLE
using php

### ISSUE THREAD

**Issue by edwardsmarkf** [nodeca/pako#102]
hello - 

this is not really an issue but more of a question.   i am trying to use[ php gzdeflate ](http://php.net/manual/en/function.gzdeflate.php)on a string:

> const compressed = ' < ? php echo  base64_encode(gzdeflate('Compress me'));  ? > '    ;
> //  compressed now contains:     c87PLShKLS5WyE0FAA==

but i cannot seem to read this string using pako:

> var enc = new TextEncoder("utf-8");
> pako.ungzip(enc.encode(compressed) );

i get this message back:  _uncaught incorrect header check_

is there a simple way to compress using generic-php and inflate using pako?

so far i have tried adding various gzdeflate "levels" from one to nine, but none of them appear to make any difference. 

thank you very much.

**Comment by puzrin** [comment]
Probably you have problem with base64 decode. Make sure compressed binary data is not corrupted.

Can't help with php, sorry.

**Comment by edwardsmarkf** [comment]
[this worked](https://stackoverflow.com/questions/44660703/using-php-gzdeflate-and-pako-js/44684128#44684128) (please feel free to upvote it)

it seems to me that using php to compress a string and using pako to uncompress could be very useful.

**Comment by edwardsmarkf** [comment]
i have been passing very large php objects (several megabytes) into jScript using pako and having much success.

to do so, i just use this one line of code:

`var     outputObject            = JSON.parse    (atos   (pako.ungzip    (atob(  '<?=base64_encode(gzdeflate(json_encode($outputObject), 6, ZLIB_ENCODING_DEFLATE))    ;?>'))));`


the jScript atos function came [from here](https://stackoverflow.com/questions/14028148/convert-integer-array-to-string-at-javascript)
