### ISSUE TITLE
Unable to inflate string (incorrect header check) from node js

### ISSUE THREAD

**Issue by Rainmen-xia** [nodeca/pako#104]
hello，
I try to compress big string on websocket by pako.
At first ,I had compressed the string correctly by  following the example;
**but here is the question 1:**
before compressed ,the length of the string is 66888,
after compressed ,the length of the string is 7000;
but when I sent the string by websocket using socket.io 
the bandwidth has increased ;
I do not why?
here is the code of server:
`
ws.on('connect', function(client) {

  setInterval(function(){

        var time = new Date().getTime();
        var i = 0;
        var message = [];

        for(;i<1000;i++){
               message.push({
                    tempx: parseInt(Math.random()*100),
                    tempy: parseInt(Math.random()*100),
                    openid: 'fjbdsaf'+parseInt(Math.random()*100)+'sfnj21321312',
                    buff: parseInt(Math.random()*100)
                })
        }

        var string = JSON.stringify(message);
        var bstring = pako.gzip(string, {to: 'string'});
        client.emit('message',tstring);

    },50)

})
`
here is the code of client:
`
socket.on('message', function(msg){
    console.log(msg);

});
`

Was it the encoding needed to be decoding in  communication of websocket？

then,I encoded the string data to 'base64';
but the browser can not deflate the data?
error"incorrect header check"
here is the code of server:
`
ws.on('connect', function(client) {
  setInterval(function(){

        var time = new Date().getTime();
        var i = 0;
        var message = [];

        for(;i<1000;i++){
               message.push({
                    tempx: parseInt(Math.random()*100),
                    tempy: parseInt(Math.random()*100),
                    openid: 'fjbdsaf'+parseInt(Math.random()*100)+'sfnj21321312',
                    buff: parseInt(Math.random()*100)
                })
        }

        var string = JSON.stringify(message);

        var bstring = pako.gzip(string, {to: 'string'});

         var tstring =  new Buffer(bstring);
         tstring = tstring.toString('base64');
         console.log(tstring);
        client.emit('message',tstring);

    },50)

})
`
and here is the code of client:
`
socket.on('message', function(msg){
     var strData     = atob(msg);  
    var data        = pako.inflate(strData,{to:'string'});  
});
`
so ,why cannot inflate correctly? Was it wrong way I used pako?

**Comment by puzrin** [comment]
I can not comment about websockets and so on. If you need JS strings compression, there is example with explanations https://github.com/nodeca/pako/tree/master/examples

**Comment by Rainmen-xia** [comment]
@puzrin I am sorry,I tried to send a compressed string from server tozrin to client,but your example is reverse； Can you give me another example,thanks a lot!^_^
