### ISSUE TITLE
Update benchmarks info

### ISSUE THREAD

**Issue by puzrin** [nodeca/pako#112]
After https://github.com/nodeca/pako/pull/106, sync zlib call show better results.

**Comment by haraldreingruber** [comment]
Would be great if you update the new numbers also in the Readme.

Also, it would be very helpful if you elaborate a bit on how to interpret the numbers.
Does ops/sec mean how often the test has been executed per second? If so, is it safe to assume that 
Pako deflate/inflate is approx. between 1.5 and 2 times slower compared to zlib?
Does the benchmark compare against the Node.js Zlib binding?

Thanks for your help 😃👍
