### ISSUE TITLE
need external access to ./utils/strings

### ISSUE THREAD

**Issue by ahicox** [nodeca/pako#113]
I'm still learning git, etc ... I patched my copy of pako.js and I think others would find it useful. My apologies is this isn't the correct place to post it:

Inside the constructor for the Deflate class, I added this:

  `this._stringUtilities = strings;`
(line 127 in ./dist/pako.js)

I did that so I can externally convert arbitrary strings to Uint8Array in the exact same format that pako.js is doing it. This is needed if you want to externally chunk a string so that you can asynchronously feed chunks to the Deflator ... 

I found this necessary because I have an app with about 30MB of json that I need to compress and stash in localstorage. When you feed data that big to Deflate, it locks execution until the entire thing completes, which makes the users think the app is dead.

I very much doubt that my hack is the correct way to expose the strings functions, but again I'm still learning. Here's how I used external access to the strings functions to create a progress indicator for Deflate:

```
// count chocula ain't got nothin' on this
try {
    var serialized = JSON.stringify(aBigStringOData);
}catch (evt){
    // gracefully handle serialization failure
}

//instantiate pako, uri encode, then binary encode the data 
try {
    var myDeflator = new window.pako.Deflate({to:'string'});
    var binData = myDeflator._stringUtilities.string2buf(unescape(encodeURIComponent(serialized)));
}catch (e){
    // gracefully handle instantiation or conversion failure
}

// feed chunks to the compressor stream asynchronously so we can track process
let myLastPct = 0;
function feedNextChunk(bufPtr){
    let final = false;
    if ((bufPtr + myDeflator.options.chunkSize) >= binData.length){ final = true; }
    try {
        myDeflator.push(binData.subarray(bufPtr, (bufPtr + myDeflator.options.chunkSize)), final);
        if (myDeflator.err){ throw new Error(myDeflator.err); }
    }catch (e){
        // gracefully handle chunk compression error
        return(false);
    }

    // update a progress bar or something, but only if the rounded percent complete actually changed
    if (myLastPct < Math.round((bufPtr/binData.length)*100)){
        myLastPct =  Math.round((bufPtr/binData.length)*100);
        console.log("compressing "  + serialized.length + " bytes. [ " + myLastPct + " %]");
    }

    // if this was the last one, assign the result and exit
    if (final){
        var compressed = myDeflator.result;

        /*
            do something with your compressed data, like invoke a callback or something
        */
        
        return(true);
    }else{

        // asynchronously push the next chunk
        window.setTimeout(function(){
            feedNextChunk(bufPtr += myDeflator.options.chunkSize);
        }, 1);
    }
}

// kick it off
feedNextChunk(0);

```

**Comment by puzrin** [comment]
In node you can just use `require("pako/lib/utils/string")`.

**Comment by ahicox** [comment]
but I'm not in node?

**Comment by puzrin** [comment]
You can write as for node, then bundle with browserify or webpak. Those files in `dist` are for legacy use, and autogenerated.

**Comment by ahicox** [comment]
hmm, ok, I'll have to read up on browserfy and webpack.
Thanks for your patience, I'm still learning this whole ecosystem.

So what you're suggesting is that I create like ... a wrapper module that has 
`require("pako/lib/utils/strings");`

then use browserfy or webpack to wrap that module for use in the browser?
