### ISSUE TITLE
pako and fsevents

### ISSUE THREAD

**Issue by paqogomez** [nodeca/pako#116]
I have an ionic project that is working on a mac installation, but I am moving the environment over to windows.

While trying to install pako@latest I get the following:

> C:\dev\[project]>npm install pako@latest
npm ERR! path C:\dev\[project]\node_modules\fsevents\node_modules\ansi-regex\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\dev\[project]\node_modules\fsevents\node_modules\ansi-regex\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\dev\[project]\node_modules\fsevents\node_modules\ansi-regex\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\dev\\[project]\\node_modules\\fsevents\\node_modules\\ansi-regex\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\dev\\[project]\\node_modules\\fsevents\\node_modules\\ansi-regex\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[me]\AppData\Roaming\npm-cache\_logs\2017-09-26T22_01_25_419Z-debug.log

I am already running as administrator.  The problem I believe is that fsevents is not supported on windows.  Its traditionally optional in other packages, but perhaps here its required?

Is there a workaround for this, or have i just missed something?

node -v - v8.2.1
ionic -v  - 3.12.0
npm -v - 5.4.0

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/blob/master/package.json#L47 pako has no dependencies

**Comment by paqogomez** [comment]
I've not found the exact answer just yet.  But it is likely something here:

https://github.com/npm/npm/issues/17671

**Comment by paqogomez** [comment]
Indeed, updating to NPM 5.4.2 fixed this.
