### ISSUE TITLE
Raw inflate errors with 'invalid stored block lengths'

### ISSUE THREAD

**Issue by dpk** [nodeca/pako#122]
## Test case

I generated a raw compressed version of the ascii string 'hello world' with Python's zlib module:

```python
>>> print(repr(list(zlib.compress(b"hello world"))))
[120, 156, 203, 72, 205, 201, 201, 87, 40, 207, 47, 202, 73, 1, 0, 26, 11, 4, 93]
```

But in the browser with pako that doesn't work:

```javascript
pako.inflateRaw(new Uint8Array([120, 156, 203, 72, 205, 201, 201, 87, 40, 207, 47, 202, 73, 1, 0, 26, 11, 4, 93]));
// pako_inflate.js:3256 Uncaught invalid stored block lengths
```

This happens with real data too (in this case I was loading it in from a file I'd compressed with Zopfli).

(This is with `pako_inflate.js` loaded, version 1.0.6.)

**Comment by dpk** [comment]
Okay, sorry, seems I misunderstood the purpose of `inflateRaw`. Normal `inflate` works fine.

**Comment by puzrin** [comment]
Test suite includes compare with native zlib in all possible modes :).
