### ISSUE TITLE
pako fails to inflate if original file is > 2G

### ISSUE THREAD

**Issue by LarryMartell** [nodeca/pako#124]
If I zip a file greater then 2G and try to inflate it fails with:

> 
> pako.min.js:1 Uncaught invalid stored block lengths
> n @ pako.min.js:1
> a.inflateRaw @ pako.min.js:1
> success @ ui.js:1122
> l @ jquery-1.8.3.min.js:2
> fireWith @ jquery-1.8.3.min.js:2
> T @ jquery-1.8.3.min.js:2
> r @ jquery-1.8.3.min.js:2

**Comment by puzrin** [comment]
I'm not sure JS engine will always allow you allocate 2G of RAM. Can you provide a code sample how to reproduce this?

**Comment by LarryMartell** [comment]
Not sure how to do that. My app is a django app. There is checkbox which when checked makes an ajax call. The python code that receives that request pulls some data form a db, converts it to json and sends back a response. Here is the snippet from my python code:

> filename = 'jsonzip'
>                 zip_response = HttpResponse(content_type='application/jsonzip')
>                 zip_response['Content-Disposition'] = (
>                     'attachment; filename=%s' % filename + '.zip')
>                 jsonstr = ""
>                 jsonstr = json.dumps(result)
>                 archive = zipfile.ZipFile(zip_response, 'w', zipfile.ZIP_DEFLATED, allowZip64=True)
>                 archive.writestr(filename, jsonstr)
>                 archive.close()
>                 return zip_response

Then on the client side I have this ajax success function:

> 
>                     success: function (text) {
>                         if (text.indexOf("PK") == 0) {
>                             filename = "jsonzip"
>                             start = text.indexOf(filename) + filename.length
>                             str = pako.inflateRaw(text.slice(start,-4), {to:"string"});
>                             waferjson = $.parseJSON(str)
>                         }

**Comment by puzrin** [comment]
@LarryMartell i'm not sure that problem is in pako. So, need minimal possible example how to reproduce of close issue.

**Comment by LarryMartell** [comment]
In my app the data comes from the server. I don't know how to create stand alone JS code that has a variable with zipped data that originally was > 2G. The zipped size is 5M. I did some testing and if the original data is < 2G it works. I only get that error when original data is > 2G.

**Comment by puzrin** [comment]
- You could post your zipped test data. But i'm busy and can't promiss to instect it soon.
- You can try to use https://github.com/Stuk/jszip instead (it has pako inside), it hides some low level browser deals. May be it has tests for huge files.

**Comment by wmhilton** [comment]
You aren't using a 32-bit browser on Windows by any chance are you?

**Comment by LarryMartell** [comment]
Good call! Indeed I was using a 32 bit chrome on windows when I was testing. I normally never use windows, but I had to for this as I had to be on a VPN I could only get on with windows to access the server. On my Mac I have a 64 bit chrome, but the code had been changed to reduce the data size and it's not >2G any more. When I have a chance I will try it with data > 2G on a 64 bit browser to make sure it works and I will let you know.

**Comment by puzrin** [comment]
IMHO it worth to close this as not related to pako (improper memory management in external program). Pako has streaming internals, not depending on data size. Chunk size is 16kb by default.

**Comment by LarryMartell** [comment]
I am testing on 64 bit browser now. Will confirm that it works and if so close this.

**Comment by puzrin** [comment]
Closing - timed out.
