### ISSUE TITLE
pacc-0.2.9.tgz on npm

### ISSUE THREAD

**Issue by NelsonLamprecht** [nodeca/pako#125]
I have some nested project dependencies that seem to depend on https://registry.npmjs.org/pako/-/pacc-0.2.9.tgz. Updating them is out of my control...any thoughts on republishing version 0.2.9 to npm? 

https://registry.npmjs.org/pako/-/pacc-0.2.9.tgz

**Comment by puzrin** [comment]
`npm install pako@0.2.9` works as needed.
