### ISSUE TITLE
Improved streaming inflate

### ISSUE THREAD

**Issue by mariusGundersen** [nodeca/pako#126]
I've looked at the js-git usage of pako, as I'm working on es-git, a js-git fork, and I'm forced to do tinflating he same way as js-git, which isn't very efficient. The way git works it doesn't specify the size of the compressed blob, only the original blob size. It's therefore not possible to know upfront how many bytes to send to inflate, instead it relies on inflating knowing when it has received the last byte:

```js
function write(byte) {
    b[0] = byte;
    inf.push(b);
    return !inf.ended;
}
```

But pushing one byte at a time is slow, it would be better to send in a long Uint8Array. That can be done, if the Inflate instance can tell how many bytes it has read before it reached the end, then it would be possible to send in large chunks at a time and then rewind whatever is left over in the Uint8Array.

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/tree/master/lib/zlib you can use `zlib` directly and create your custom wrapper. Default ones are for simplified use and can not cover all possible cases.

**Comment by mariusGundersen** [comment]
Hmm, is there a property in the inflate state that counts bytes read?

**Comment by puzrin** [comment]
I don't remember such details. It's better to inspect original zlib, this is it's very exact port with some minor features skipped.

**Comment by mariusGundersen** [comment]
Just in case someone stumbles across this issue looking for the same thing, this is how I solved it:

```js
const inf = new pako.Inflate();
do {
  inf.push(await state.buffer.chunk());
} while(inf.err === 0 && inf.result === undefined);
state.buffer.rewind(inf.strm.avail_in);
```

The useful part here is the `inf.strm.avail_in`, which contains the number of bytes remaining in the `UInt8Array` passed to `inf.push()`. There is also a `inf.strm.next_in`, which contains the number of bytes alread read from the input. In other words, `next_in + avail_in = input.length`.
