### ISSUE TITLE
incorrect header check

### ISSUE THREAD

**Issue by danielloczi** [nodeca/pako#127]
I'm trying to use the latest version (1.0.6) of your library in a React project.
For some reason Pako always reports 'incorret header check' when I try to process the result of a deflated WebAPI call.

I also tried the following code snipet, but getting the same error:
```
import Pako from 'pako'; 

....

let response = await fetch('http://httpbin.org/deflate');
let binaryData = await response.arrayBuffer();
let uintArray = new Uint8Array(binaryData);
let uncompressedData = Pako.inflate(uintArray, { to: 'string' });
console.log(uncompressedData);
```

Can you please help me to figure out what is the problem with the example above?

**Comment by puzrin** [comment]
There are 2 main reasons of such errors:

- use inflate instead of inflateRaw (or reverse)
- input data is really incorrect.

IMHO fetch returns already inflated result.
