### ISSUE TITLE
Usage question - JSON XHR upload

### ISSUE THREAD

**Issue by murraybauer** [nodeca/pako#128]
I am struggling to use Pako in a browser client to deflate a large JSON object for upload to a node.js server and inflate again as JSON.

The example says to base64 encode the binary from defalte for XHR.  

I tried the below using your example add just added the base64 encode and decode all in node.js and on inflate it always errors with `incorrect header check` 

Any pointers?  I've tried some many alternative library's and cant get any to work across browser and server.

```
var pako = require('pako');
var test = { my: 'super', puper: [456, 567], awesome: 'pako' };

var binaryString = pako.deflate(JSON.stringify(test), { to: 'string' });

//
// Here you can do base64 encode, make xhr requests and so on.
//
  var encoded = new Buffer(binaryString).toString('base64');
  var decoded = new Buffer(encoded, 'base64')
  
  var restored = JSON.parse(pako.inflate(decoded, { to: 'string' }));
```

**Comment by puzrin** [comment]
Sorry, that's not related to this package, can't help with XHR and other browser programming,. The only thing i could do about this is already placed into `/examples` folder.
