### ISSUE TITLE
TextEncoder & TextDecoder

### ISSUE THREAD

**Issue by bp74** [nodeca/pako#131]
First of all, thank you very much for this great library!

I'm working on a project where i inflate very long strings and i wonder if you would consider adding support for TextEncoder and TextDecoder? This API is supported by all major browsers (only Edge is missing, but already under development) and you could use the current implementation as a fallback.

https://caniuse.com/#search=TextDecoder
https://encoding.spec.whatwg.org/

**Comment by puzrin** [comment]
I see no reasons. Don't like to add code just for fun. If you have suggestion, please descrribe it in terms "added values", not as "add cool function call"

**Comment by bp74** [comment]
well, i thought the added value is quite obvious - it's performance of course.

**Comment by puzrin** [comment]
You are expected to provide estimate, how much performance will be improved. Talks about performance without benchmarks are waste of time :)

**Comment by bp74** [comment]
Here you can get an impression of the performance advantage:
https://jsperf.com/encodingapi/1

Of course it depends how long your string is. If the string is short (1KB) you will get a >5x improvement, If the string is long (1MB) the improvement is much higher.

**Comment by puzrin** [comment]
@bp74 nobody cares about such tests. If you claim that performance will be better, your proofs should show that __pako__ calls become faster (and how much). If pako calls do not improve much, then it's not significant even if text conversion become 1000000 times faster.

**Comment by bp74** [comment]
okay forget it.

**Comment by Ruffio** [comment]
@puzrin what kind of attitude is that? Here you have an user that suggests an improvement and then you just mock him?

**Comment by bp74** [comment]
thanks @Ruffio , i thought exactly the same. The answers were very unfriendly and i tried to provide the necessary feedback. In the end i was really frustrated.

**Comment by alippai** [comment]
I'm sure @puzrin only wants to emphasize, that you have to really good reason to add a new API to a stable library. Linking that benchmark doesn't help him to understand the TextEncoder implications on pako performance. I'm happy to do the benchmark and the PR (maybe only in April).

**Comment by puzrin** [comment]
@Ruffio

> Here you have an user that suggests an improvement and then you just mock him?

At first, everyone, including you, spend my time for free, when come to this tracker. He can spend it for good things or waste it. If someone wish to do good things, all suggestions about performance MUST include correct benchmark or any other kind or correct proof.

**Comment by puzrin** [comment]
@alippai i'm not sure that recoding is significant part of all process. So, attempt to improve it will be a kind of micro-optimization. But if you are interested - no problem. Good benchmark will have more weight than my assumptions.

**Comment by puzrin** [comment]
@alippai also note, binary string interface was done for ancient browsers without typed arrays support. Because huge `String` with binary content is more optimal than `Array` there. But i'm not sure it worth use such approach in modern browsers.

**Comment by alippai** [comment]
I'm not familiar with the string interface, we use only the Uint8Array based one. I expect that this issue will result only in a new readme part, that converting your string data with TextEncoder before calling pako is a performance best practice. The current JSON.parse and stringify examples may need a little update, that's all.

**Comment by puzrin** [comment]
If talk is about JSON encode, that's not supported in paco (an will not), because pako is about binary data inflate/deflate. Then i don't understand, what "performance win" was suggested (compared to what?).

> The current JSON.parse and stringify examples may need a little update, that's all.

It would be nice, if someone could PR better sample. I agree, existing one is very basic.
