### ISSUE TITLE
Uncaught buffer error

### ISSUE THREAD

**Issue by neel-radica** [nodeca/pako#133]
I am trying to decompress svgz but to no avail. 
![image](https://user-images.githubusercontent.com/32937442/38843569-3916842e-4222-11e8-8ce0-eb7d992c6118.png)

**Comment by puzrin** [comment]
No idea. I'm not familiar with svgz details.

**Comment by neel-radica** [comment]
I did deflate the svg using pako.

**Comment by puzrin** [comment]
You can do deflate with any other library, for example via node.js zlib. I'm not sure your problem is related to this package.

**Comment by neel-radica** [comment]
ok, thanks.
