### ISSUE TITLE
Ziploader - how to load a local file in the client machine

### ISSUE THREAD

**Issue by avnermosh** [nodeca/pako#134]
Hi,

I'm using ZipLoader to load a zip file from local directory on the client machine.
I found out that if the file does not exist in the server, it doesn't upload properly.

In ZipLoader, the ZipLoader.prototype.load uses xhr.open('GET', this.url, true); so I assume it goes to the server to get the file?
I also see a comment in Ziploader.js "Should I use FileReader?..." (in function ZipLoader.prototype.extractAsText()).
From what I read in the Internet, [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) or [createObjectURL(](URL.createObjectURL(file).) can be used to read files from the client machine.

Are there any restrictions or limitations to generalize ZipLoader so that it can read from loacl file system on the client machine?

Thanks

**Comment by puzrin** [comment]
Sorry, not familiar with ZipLoader. This issue does not seems to be related to this project.

**Comment by avnermosh** [comment]
My bad, ZipLoader project is using this lib, but the problem is in ZipLoader. This issue should be deleted from here but I don't know how to do that
