### ISSUE TITLE
A trick to compress faster

### ISSUE THREAD

**Issue by photopea** [nodeca/pako#135]
Since you rewrote ZLIB to JS, I expect you understand the code. I hope my explanation will be clear to you :)

There is a trick, which requires additional 32kB of RAM, but will make the compression (search for repeating strings in LZ77) much faster.

You hash 3-bytes into chains, which help you find previous occurences of these 3 bytes. But you hash 3 bytes into 8 bits, and many collisions occur (you process long chains while looking for the longest string match). I suggest to use 16 bits for hashing. There are much less collisions, shorter chains, so you find occurences faster. I suggest a following hash:

    hash = ((byte1 |  (byte2<<8)) + (byte3<<4)) & 0xffff;

Also, when you have the longest match of N bytes and search further (to larger distance) for a longer match, check the (N+1)-th byte (if it is the same) before you start checking the whole string.

**Comment by Ruffio** [comment]
Do you have any benchmarks? I don't know the algorithm in details, but generally it is a good idea with some benchmarks. Both memory usage and compression time.

It could be a good idea to implement it as an option with default as it is now. In that way devs has to actively enable it, IMHO.

**Comment by puzrin** [comment]
@photopea i think, global improvements should be adviced to original project first. Because this one is "mirror" of original with minimal deviations, caused by JS restrictions. I have no resources (time) for algorythm development, only for maintenance (sync with upstream).

To be constructive, i recommend to create test repo with suggested changes, run betchmark and make sure tests ok. If you come with real (measured) proofs about significant perf improvement, that will be not "just an idea" and completely different story.

**Comment by puzrin** [comment]
@photopea i've closed issue to keep tracker clear from "uncertain" things, tending to be open forever. But don't consider this as "i'm strongly against your proposal". I'm not against good proposals, but against endless issues. We can open it again if interesting benchmark available, or create a new one.

**Comment by photopea** [comment]
I think that ZLIB avoided it precisely because of extra 32 kB of RAM (ZLIB was made to run in low-memory environments). It doubles the size of a hash table. But I see your point.

**Comment by puzrin** [comment]
@photopea no, they have many `#ifdef`-s for specific CPU-s. I think, if opts could give significant gain,  proper patch would not be rejected.

**Comment by Ruffio** [comment]
@photopea do you have any benchmarks? It could be interesting to see the differences. If added as an option the dev. could decide speed vs. RAM usage. Mobile and desktop devices of today are much stronger and powerful compared to when zlib was released in 1995... As hardware evolves, so should software.

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/commit/4828185800b27c4687a52d49990002e5c26cb507

Hmm... FYI, with your hashed deflate become faster, but inflate become slower. I'm no 100% sure, that's preliminary result.
