### ISSUE TITLE
Is deflating ArrayBuffer allowed?

### ISSUE THREAD

**Issue by emilekberg** [nodeca/pako#138]
When trying this out in a playground i acidentally passed an ArrayBuffer to deflate instead of Uint8Array. 
I first noticed my issue when putting it into my code, which is using typescript. It then started to complain. However, I get the same result when passing my arraybuffer to the deflate and inflate functions. Is this intended or just an happy accident? I see no support of this in the documentation or such. 

for instance: 
```
const pako = require('pako');

const arrayBuffer = new ArrayBuffer(32 * Uint16Array.BYTES_PER_ELEMENT);
const view = new DataView(arrayBuffer);
for(let i = 0; i < 32; i++) {
  view.setUint16(i * Uint16Array.BYTES_PER_ELEMENT, i);
}

const compressed = pako.deflate(arrayBuffer);
const processedView = new DataView(pako.inflate(compressed.buffer).buffer);
let equal = true;
for(let i = 0; i < 32; i++) {
  const offset = i * Uint16Array.BYTES_PER_ELEMENT;
  const a = view.getUint16(offset);
  const b = processedView.getUint16(offset);
  console.log(a, b);
  equal = equal && a === b;
}
console.log(equal);
```

will output
```
0 0
1 1
2 2
.. ..
.. ..
30 30
31 31
true
```

which mean they are equal. 

Am i missing something?

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/blob/893381abcafa10fa2081ce60dae7d4d8e873a658/lib/deflate.js#L232

Yes, that's supported and seems to be documented in autogenerated docs, but not actively promoted. Just search in sources for "ArrayBuffer" to see details.

**Comment by emilekberg** [comment]
JSDoc seems to say otherwise: 
https://github.com/nodeca/pako/blob/893381abcafa10fa2081ce60dae7d4d8e873a658/lib/deflate.js#L323

https://nodeca.github.io/pako/#deflate

Could probably say ArrayBuffer there as well. this was what threw me off. It seems to be documented in Deflate.push, but not deflate and deflateRaw method.

**Comment by puzrin** [comment]
May be. I don't remember. You can make PR if corrections needed.
