### ISSUE TITLE
FR: Event emitter to get progress

### ISSUE THREAD

**Issue by nitrocode** [nodeca/pako#141]
I'm trying to follow this issue https://github.com/nodeca/pako/issues/42 but for the `gzip` function. I'm working on overriding the `onData` method and then I realized it would much easier to listen to an event emitter.

For example, look at the `httpUploadProgress` emitter with the [aws-sdk-js](https://aws.amazon.com/blogs/developer/announcing-the-amazon-s3-managed-uploader-in-the-aws-sdk-for-javascript/) package.

**Comment by puzrin** [comment]
That's a sync library. This request is not relevant.
