### ISSUE TITLE
Get progress of gzip() compression by overriding onData

### ISSUE THREAD

**Issue by nitrocode** [nodeca/pako#142]
I'm trying to follow this issue #42 but for the gzip function.

How do I do this? I get an error on the first line.

    oPako = pako.gzip();
    oPako.onData = function(chunk) {
      this.chunks.push(chunk);
    };
    oPako.push(fileContents, true);
    fileContents = null;
    Body = oPako.result;

Error

    Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

I'm currently using this for large files. Anyway I can modify this to get progress?

    Body = await pako.gzip(output.contents);

I couldn't find an event emitter so I created a separate feature request for that https://github.com/nodeca/pako/issues/141.

**Comment by puzrin** [comment]
That's a sync library. You should manually split data by small chunks, then push and increment your progress. See examples in api docs.

**Comment by nitrocode** [comment]
@puzrin  I followed the api guide's `onData` function and I get an error.

```
const deflate = new pako.Deflate({ gzip: true });

deflate.onData = (chunk) => {
  this.chunks.push(chunk);
  console.log('chunk');
};

deflate.push(contents, false);
deflate.push(contents, false);
deflate.push(contents, false);
deflate.push(contents, true);
```

```
TypeError: Cannot read property 'push' of undefined
```

What am I doing wrong?

Also once I've resolved the issue with `this.chunks` missing `push`, how do I know how much to add to the progress bar? Should I just do what [Progi1984 did here](https://github.com/nodeca/pako/issues/42#issuecomment-68698494)? 

Thanks!

**Comment by puzrin** [comment]
`(chunk) =>` should be `function (chunks)` for proper `this`.

**Comment by nitrocode** [comment]
@puzrin I did this and it worked. I called `push` 4 times and my `onData` function only ran once. Do you know why?
