### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by codepunkt** [nodeca/pako#144]
The documentation website states that `pako` is MIT licensed.
The `LICENSE` file states that `pako` is MIT licensed.
The `package.json` contradicts this and says `pako` is both MIT and Zlib licensed.

This might be a problem for enterprises, whose legal departments might also have to check for Zlib.
Which one is it? If it's just MIT, it would be wise to reflect that in the `package.json`.

**Comment by puzrin** [comment]
LICENSE file is for all subdirs except one with different info https://github.com/nodeca/pako/tree/master/lib/zlib

Could you give me exact link to documentation? Probably, that info should be clarified or removed at all.

**Comment by puzrin** [comment]
Closing - no feedback.

Also, clarified details in readme https://github.com/nodeca/pako/commit/0124206d64a6c89cb06aa8dd23e46ccdf86f6e66

**Comment by ljharb** [comment]
@puzrin the proper solution here would be to put the zlib stuff in a separate published package, with a package.json, that declares its license, and have the root declare the license as MIT.

**Comment by steffen-4s1** [comment]
Today I added pako as a dependency to a commercial application and also stumbled across the missing Zlib licence.

From my point of view, the Zlib licence must be added to the LICENSE file so that both the MIT and the Zlib licence are included there.
