### ISSUE TITLE
inflate(deflate(src)) != src

### ISSUE THREAD

**Issue by eazrael** [nodeca/pako#148]
Not sure if that is an issue or just the expected result. My expectation is inflate(deflate(src)) equals src
In my case src is the HTML text from a browser window.  

```
let html = new XMLSerializer().serializeToString(document.documentElement)
let html_utf8 = unescape(encodeURIComponent(data.html)); 

pako.inflate(pako.deflate(html)) == html
pako.inflate(pako.deflate(html_utf8)) == html_utf8
```

Both compares return false. Is that the correct result?

**Comment by puzrin** [comment]
Missed `{ to: 'string' }`. Please, read examples/docs/tests first.

**Comment by eazrael** [comment]
Sorry. Seems that I missed this. 
Thanks for the answer.
