### ISSUE TITLE
Please provide (minimal) client-side examples

### ISSUE THREAD

**Issue by Redsandro** [nodeca/pako#15]
In my case, I want to unzip some gzipped strings.
What are the minimum steps I need to do this client side / browser?

I don't understand which files I need.
I would expect just`dist/pako_deflate.min.js` but it requires files not in the `dist` directory.

Please provide a minimal example. Cooler would be examples for decode too, in the `README.MD`, but that's just thinking about other people who stumble across this interesting module - not for me.

ps I am using `requirejs` if that makes things easier.

**Comment by wvtxman** [comment]
how could you use pako to zip up multiple pdf files

**Comment by puzrin** [comment]
i think you need jszip instead - more high level lib
