### ISSUE TITLE
accented characters problem

### ISSUE THREAD

**Issue by wiim23** [nodeca/pako#151]
Hi,
Since 1.0.7, i have a problem with accented characters :
`pako.ungzip(pako.gzip("début"),{to: "string"})`

Result : "dâut"

An idea to resolve it?
Thanks by advance,

**Comment by puzrin** [comment]
Your input data for `pako.gzip()` is invalid. Those MUST be bytes, not words. For example you could recode strings to utf8 first. See example source with explanations https://github.com/nodeca/pako/tree/master/examples

**Comment by wiim23** [comment]
You're right!
`pako.ungzip(pako.gzip(new TextEncoder().encode("début")),{to:"string"})`

Like that, result is ok
Thanks
PS : i must find a better solution for cross browser now...

**Comment by puzrin** [comment]
There is a [dirty hack](https://github.com/nodeca/pako/blob/master/examples/browser.html#L30) via `unescape(encodeURIComponent(str))`.

**Comment by wiim23** [comment]
yep, 
it was the track on which I was, thanks again
