### ISSUE TITLE
Avoid magic numbers in buf2binstring

### ISSUE THREAD

**Issue by mathiasbynens** [nodeca/pako#153]
https://github.com/nodeca/pako/blob/70db11221350919781a2bfd72a9ebe75a50f0fb8/lib/utils/strings.js#L84-L100

It might be useful to avoid the magic number `65534` altogether, since it's an implementation detail that might change over time. Moreover, the number doesn't take into account the current stack size, so this approach is not entirely bulletproof to begin with.

Instead, one possible approach is to chunk up the calls to `String.fromCharCode.apply` per e.g. `10000` elements.

cc @psmarshall

**Comment by puzrin** [comment]
IMHO any number value will be magical. 10000 is not much better than 65534. At least, we commented, why such number exists. Also see https://github.com/nodeca/pako/pull/150

I don't know what can be done, so tend to close as not fixable.

**Comment by puzrin** [comment]
Also note, binary strings is legacy interface for ie6... who cares?...

**Comment by mathiasbynens** [comment]
> IMHO any number value will be magical. 10000 is not much better than 65534.

IMHO it _is_ better, because a) something like `10000` is not as close to the limit as the limit itself, and b) it's a number that you specify that is unrelated to engine implementation details.

> binary strings is legacy interface for ie6... who cares?...

The code I referenced has a comment about modern Chrome.

---

Feel free to close this issue; I just wanted to make the suggestion. Thanks for your work on this project!

**Comment by puzrin** [comment]
> The code I referenced has a comment about modern Chrome

I mean, any "modern" code should use typed arrays for input-output instead of binary strings. In this case that part of code will never be called.

> Feel free to close this issue; I just wanted to make the suggestion. Thanks for your work on this project!

Let's close. I know, that peace of code is ugly, and nothing can do it much better.
