### ISSUE TITLE
inflateRaw with dictionary fails

### ISSUE THREAD

**Issue by Xubor** [nodeca/pako#155]
While `inflate` function is working when used with dictionary, `inflateRaw` function fails. Function `deflateRaw` (with dict) is probably correct, as it produces the same output as zlib.

Example:

```javascript
const pako = require('pako');
const zlib = require('zlib');

const dict = "test";
const str = "testestestestestestest";

console.log("Tests with dictionary");

const deflated = pako.deflate(str,{dictionary:dict});
const inflated = pako.inflate(deflated,{dictionary:dict});
console.log("pako deflate/ pako inflate == source: " + (String.fromCharCode.apply(null,inflated) == str));

const zlibDeflated = zlib.deflateSync(str,{dictionary:Buffer.from(dict)});
console.log("pako deflate == zlib deflate: " + (Buffer.compare(zlibDeflated,Buffer.from(deflated)) == 0));

const deflatedRaw = pako.deflateRaw(str,{dictionary:dict});
const zlibDeflatedRaw = zlib.deflateRawSync(str,{dictionary:Buffer.from(dict)});
console.log("pako deflateRaw == zlib deflateRaw: " + (Buffer.compare(zlibDeflatedRaw,Buffer.from(deflatedRaw)) == 0));

const inflatedRaw = pako.inflateRaw(deflatedRaw,{dictionary:dict});
console.log("pako deflateRaw/ pako inflateRaw == source: " + (String.fromCharCode.apply(null,inflated) == str));
```

Output:
```
Tests with dictionary
pako deflate/ pako inflate == source: true
pako deflate == zlib deflate: true
pako deflateRaw == zlib deflateRaw: true

./node_modules/pako/lib/inflate.js:384
  if (inflator.err) { throw inflator.msg || msg[inflator.err]; }
                      ^
invalid distance too far back
```

**Comment by puzrin** [comment]
I'd suggest first to check how to execute inflate raw without dictionary option. Probably you should pass compression options to make it work.

**Comment by Xubor** [comment]
I have tried as you suggested.   
There are no problems executing plain `inflateRaw` without dictionary.   
With dictionary, the resulting error is the same when used with compression options, e.g. `{dictionary:dict,level:6,strategy:0,windowBits:10,memLevel:8,chunkSize:16384}`.    
Only exception is using `level=0`, where there is no problem, but that is no surprise as input is not compressed at all.   
The zlib version of `inflateRaw` is working with dictionary without problems, even when the compression options are not specified.

**Comment by puzrin** [comment]
As far as i remember, dictionary support to wrapper was added by someone else. I have no plans to investigate, but PR with improvement will be accepted.

**Comment by Xubor** [comment]
It seems exactly this one is waiting: https://github.com/nodeca/pako/pull/120

**Comment by puzrin** [comment]
Seems yes. As soon as anyone do PR with tests (coverage), it will be possible to merge it.

**Comment by puzrin** [comment]
Also, i did not understood - is it really needed to load dict differently for RAW and notRAW modes.
