### ISSUE TITLE
GZiping a Float32Array

### ISSUE THREAD

**Issue by m4nuC** [nodeca/pako#157]
I've tried gzipping a large` float32array` and inflating it back apparently without any loss. So I am wondering what is the reason fro `float32array` to not be supported ? Maybe they can't be compressed by much ?

**Comment by puzrin** [comment]
That's not math library. It needs bytes. How do you create those bytes is out of library scope.

**Comment by m4nuC** [comment]
Thanks for your reply. So basically to reformulate, any type of input is fine but output types are restricted. Is that correct ? If so, should the documentation and typings reflect this ?

**Comment by puzrin** [comment]
> any type of input is fine but output types are restricted.

NO. Package needs bytes on input and return bytes on output (Uint8Arrays). It has some MINOR tweaks for compatible legacy formats (byte strings), not recommended to use.

Please, google how deflate works and inspect top level source (it's very small). IMHO you invent not existing problems.

**Comment by m4nuC** [comment]
Isn't everything bytes ? Not inventing problems, just asking a simple question, hoping for simple answer.
