### ISSUE TITLE
Pako unexpectly reversing bytes when given string

### ISSUE THREAD

**Issue by hbergren** [nodeca/pako#158]
Pako can take a string for `deflate()`, and automatically turn it into an `Uint8Array` internally for compression purposes.

So when I call `pako.deflate("⛄🤔✔")`

It passes the correct array to `strm.data`:

```js
strm.data = strings.string2buf("⛄🤔✔")
=> Uint8Array(10) [ 226, 155, 132, 240, 159, 164, 148, 226, 156, 148 ]
```

### Problem

When you use this array as your initial data, everything works as expected, and your input matches your output:
```js
pako.inflate(pako.deflate([ 226, 155, 132, 240, 159, 164, 148, 226, 156, 148 ]))
=> [ 226, 155, 132, 240, 159, 164, 148, 226, 156, 148 ]
```

However, when you attempt to do this on the original unicode string, the bytes of each unicode character get reversed:
```js
pako.inflate(pako.deflate("⛄🤔✔"))
=> [ 132, 155, 226, 148, 164, 159, 240, 148, 156, 226 ]
```

So `[226, 155, 132]` becomes `[132, 155, 226]`.

Why is this happening? In both cases, the same array is being passed to `strm.data`:

https://github.com/nodeca/pako/blob/master/lib/deflate.js#L228-L236

**Comment by puzrin** [comment]
Pako needs binary data, and don't know about strings encoding. Supported strings are for ancient IEs and are binary strings (1 byte per char).

If you need to pack multibyte strings (for example, JS strings are UTF-16), you should care how to convert those to binary strings or typed array (abd to the same back on inflate). See https://github.com/nodeca/pako/tree/master/examples

**Comment by hbergren** [comment]
Doesn't Pako convert those to a typed array by default using `strings.string2buf`?

https://github.com/nodeca/pako/blob/master/lib/deflate.js#L231

I'm just trying to understand why the output of `pako.deflate()` is different when you pass a string vs the "equivalent" `Uint8Array`, when the `strm.input` for these two cases is identical:

https://github.com/nodeca/pako/blob/master/lib/deflate.js#L231-L235

**Comment by puzrin** [comment]
Because you try to feed it with 16-bit strings, and pako uses lower byte only. If you pass english text (ascii), it will work.
