### ISSUE TITLE
Text garbling Japanese by inflate() only in pako.min.js

### ISSUE THREAD

**Issue by nwtgck** [nodeca/pako#160]
Hi, developers! Thank you for your wonderful project. pako is very useful!

Japanese characters are text garbled (maybe multi-byte characters are) only in `pako.min.js` in version 1.0.8.

Here is sample code for this issue.

```html
<html>
   <!-- .min.js not work -->
  <script src="node_modules/pako/dist/pako.min.js"></script>
   <!-- .js works! -->
   <!-- <script src="node_modules/pako/dist/pako.js"></script> -->
  <script>
    const plainText         = "これは日本語です。"
    const compressedBinText = pako.deflate(plainText, {to: 'string', level: 9, windowBits: -8});
    const decompressedText  = pako.inflate(compressedBinText, {to: 'string', windowBits: -8});
    
    // They should be the same
    console.log(plainText);
    console.log(decompressedText);
  </script>
</html>
```

In the sample, `plainText` and `decompressedText` should be the same value. However, they are not the same in `pako.min.js` in 1.0.8.

Here is a console log in Chrome in macOS.

### Using pako.min.js

<img width="125" alt="screen shot 2019-02-18 at 20 56 03" src="https://user-images.githubusercontent.com/10933561/52949482-baf68900-33bf-11e9-8411-881f744a4d8a.png">

### Using pako.js

<img width="118" alt="screen shot 2019-02-18 at 20 55 09" src="https://user-images.githubusercontent.com/10933561/52949490-c34ec400-33bf-11e9-8bfa-2e8e9181ee53.png">

---

I made public whole code of the sample code in <https://github.com/nwtgck/public-code/tree/master/pako-garbling/pako-1.0.8>. It may make easy to test in other platforms.

**Comment by puzrin** [comment]
You should reencode your text to 8-bit format (utf-8, for example). Then do reverse after unpack.

See https://github.com/nodeca/pako/tree/master/examples

**Comment by nwtgck** [comment]
@puzrin Thanks for your kind description and the link.

In pako.min.js in version 1.0.6, it worked well. Did pako change the specification?

**Comment by puzrin** [comment]
You can check commits log. There were no spec change. I'd suggest to fix your code first, because missed reencoding is obvious problem.

**Comment by nwtgck** [comment]
@puzrin Thank you very much for your suggestion. I'll fix it.

**Comment by nwtgck** [comment]
@puzrin Do you have some reason why the behavior `pako.js` and `pako.min.js`are different in 1.0.8, but in 1.0.6 is the same?

**Comment by puzrin** [comment]
No ideas. I can't imagine how could it work at all. That's technically impossible, if you not limited texts to english letters only.

**Comment by nwtgck** [comment]
@puzrin Thank you for telling me. But in my opinion, wrong usages are not guaranteed its behavior, so I think I should correct my app. However, the behavior I reported may imply a potential bug in pako.

**Comment by puzrin** [comment]
Sorry, i forgot everything about pako :). Seems it has some buit-in strings support and realy can eat JS strings.

Let's continue tracking in #161, will fix soon.

**Comment by nwtgck** [comment]
@puzrin Thak you for your so good support! I'll try 1.0.10 https://github.com/nodeca/pako/issues/161#issuecomment-468450593.
