### ISSUE TITLE
receipe for iterating over a large gzipped text file

### ISSUE THREAD

**Issue by sakoht** [nodeca/pako#163]
I'm attempting to have a browser app read a 2G file that decompresses to 10G (too big for browser memory), and examine it before posting it to S3.

The AWS libs handle these big things nicely doing a parallelized multipart upload, but I'm having trouble using pako to do the upfront checks.  Things work on smaller files where I can decompress the whole thing into RAM and then split it up.

Do you have a recipe for streaming an arbitrarily large `.gz` file, possibly firing a callback on each line?

I can read the file in chunks and feed it to pako Inflate, but how do I get intermediate results and flush things as I go?

Thanks for advice.  Your library is quite impressive to pull this off in the browser.

**Comment by puzrin** [comment]
See http://nodeca.github.io/pako/#Deflate.prototype.onData

Look into source code and override default methods for your needs.

**Comment by sakoht** [comment]
I see there is an onData for Inflate, but there is nothing I see in the docs for how to use it appropriately.

**Comment by puzrin** [comment]
Please, look into source code first, to see how it's used by default.
