### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by natiki** [nodeca/pako#165]
[This package](https://www.jsdelivr.com/package/npm/pako) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by puzrin** [comment]
https://github.com/jsdelivr/jsdelivr/pull/2317 jsDelivr is maintained by different people, ask there.

**Comment by natiki** [comment]
@puzrin The issue is that the package.json does not contain an entry specifying the default filename because none of the fields:

* jsdeliver
* browser
* main

See https://www.jsdelivr.com/features#publishing-packages. As JsDeliver scans your package.json it is not a jDeliver issue it is ultimately that you need to amend package.json.

**Comment by puzrin** [comment]
https://stackoverflow.com/a/22513200/1031804

`main` is required only for non standard entry points. If jsdeliver scripts can not process defaults properly, that's not this package issue.

**Comment by natiki** [comment]
@puzrin Its up to you, but the point of the exercise is to make the library more widely used? 

So to keep things "pure" why not then add the jsdeliver field so that the library will be more easily served up by jsDeliver?

**Comment by puzrin** [comment]
- because it's bad practice to use kludges instead of fix original thing
- because original PR has appropriate patch and you did not provided any proof of real problem - you just come with abstract statements about bug.
