### ISSUE TITLE
CDN JsDelivr is not updated with release 1.0.10 of pako

### ISSUE THREAD

**Issue by f18m** [nodeca/pako#168]
Hi,
I could find only
   https://cdn.jsdelivr.net/pako/1.0.5/pako.min.js
as the latest release from JsDelivr.net.
I tried to get
 https://cdn.jsdelivr.net/pako/1.0.10/pako.min.js
without success.

I think also your HTML example is still using release 1.0.3...

**Comment by alexeyten** [comment]
https://cdn.jsdelivr.net/npm/pako@1.0.10/dist/pako.min.js

**Comment by f18m** [comment]
I didn't know that, thanks!

PS: you may consider updating your HTML example as well...
