### ISSUE TITLE
Inflate issues in Zlib for Ruby

### ISSUE THREAD

**Issue by poplinnilpop** [nodeca/pako#169]
Hey Pako Team,

I used ```pako.deflate(JSON.stringify(data), { to: 'string' })``` to compress a JSON payload and am able to open it up correctly over a REST call by using ```JSON.parse(pako.inflate(binaryString, { to: 'string' }))``` via another Node.js service successfully.

However, when trying to inflate and view the JSON in a Ruby environment, I'm consistently getting ```'inflate': incorrect header check (Zlib::DataError)```. So, in general, how does one get this data viewable from a potentially different language driven micro service by using Zlib (or is there another package that can do this...)?

Thanks!

**Comment by puzrin** [comment]
I don't know ruby. The only thing i can say - result is binary equal to zlib's one. Make sure you use proper decoder (not RAW deflate). Or try use `gzip`, because it has no "alternate" method.
