### ISSUE TITLE
【help wanted】Lost Part of Data

### ISSUE THREAD

**Issue by cctv1005s** [nodeca/pako#173]
i use `deflate` and  `window.btoa`  to transfer a string to a shorter base64 string and spilt it to many parts  (about 1kb per part, 58kb total).

Unfortunately I lost one part of it.

Is there any way I can recover my data ?

**Comment by puzrin** [comment]
Please provide a minimal executable code sample. Also, see tests for reference.

**Comment by cctv1005s** [comment]
i think it is a impossible task...
