### ISSUE TITLE
Uncaught buffer error

### ISSUE THREAD

**Issue by softshape** [nodeca/pako#177]
Hi all,

trying to download and gunzip SVGZ which is actually Gzip'ed SVG (test file here - https://m.baikal.live/img/comet.svgz). The code looks like:

```
 var arr = new Uint8Array(data);
 var plain = pako.inflate(arr, { to: 'string' });
```
The result is 'Uncaught buffer error' or 'incorrect header check' (if I try other combinations) in the console. What is the correct code to unpack SVGZ to string?

**Comment by puzrin** [comment]
Check your input data in array constructor is really valid. Also, worth to provide executable code instead of description.

**Comment by softshape** [comment]
Just found that this is some incompatibility with Pixi loader which is loading the images in our code. Pure XHR code works just fine:
```
  var xhr = new XMLHttpRequest();
  xhr.open("GET", '../comet.svgz', true);
  xhr.responseType = 'arraybuffer';
  xhr.addEventListener('load',function(){
    if (xhr.status === 200){
      var byteArray = new Uint8Array(xhr.response);
      var svg = pako.inflate(byteArray, {to: 'string'});
      console.log('SVG', svg);
    }
  })
  xhr.send();
```
