### ISSUE TITLE
c# can`t unzip the http requet Body stream

### ISSUE THREAD

**Issue by jol5** [nodeca/pako#178]
1.
Thanks！！！
js:
var test = { my: 'super', puper: [456, 567], awesome: key };
var binaryString = pako.deflate(JSON.stringify(test), { to: 'string' });

fetch('http://127.0.0.1:8080/api/values/TestPost', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/gzip'
  },
  body: params
}).then(function(response) {
  console.log(response);
});

cs:
using (GZipStream stream = new GZipStream(context.Request.Body, CompressionMode.Decompress)) {
                using (StreamReader reader = new StreamReader(stream, Encoding.UTF8))  {
                    text = reader.ReadToEnd(); // this will throw an error:System.IO.InvalidDataException:“The archive entry was compressed using an unsupported compression method.”
                }
            }

**Comment by puzrin** [comment]
Sorry, can't help about c#. Only couple of notes:

- Make sure received data is the same as been sent.
- Try to send Uint8Array (defaut), `fetch` should support that.
- gzip & deflate have different headers and checksums. Make sure use proper compress and decompress methods.

**Comment by Dams591** [comment]
Hey @jol5 
I'm trying to do the same and also facing an issue, did you find a solution to this ? 
Thank you

**Comment by jol5** [comment]
> Hey @jol5
> I'm trying to do the same and also facing an issue, did you find a solution to this ?
> Thank you

    export function zip(str:string){
        if(!isString(str)) str = JSON.stringify(str);
        var binaryString = gzip(str, { to: 'string' })
        return btoa(binaryString);
   }

c#
  var memery = new MemoryStream();
                context.Request.Body.CopyTo(memery);
                memery.Position = 0;
                var reader = new StreamReader(memery);
                var requestBodyAsString = await reader.ReadToEndAsync();
                context.Request.Body.Dispose();

                var unzipString = ZipUtil.GZipDecompressString(requestBodyAsString);
                reader.Close();
                memery.Dispose();

//////////////////////////////////
        public static string GZipDecompressString(string zippedString)
        {
            if (string.IsNullOrEmpty(zippedString) || zippedString.Length == 0)
            {
                return "";
            }
            else
            {
                byte[] zippedData = Convert.FromBase64String(zippedString.ToString());
                return (string)(System.Text.Encoding.UTF8.GetString(Decompress(zippedData)));
            }
        }

        public static byte[] Decompress(byte[] zippedData)
        {
            MemoryStream ms = new MemoryStream(zippedData);
            GZipStream compressedzipStream = new GZipStream(ms, CompressionMode.Decompress);
            MemoryStream outBuffer = new MemoryStream();
            byte[] block = new byte[1024];
            while (true)
            {
                int bytesRead = compressedzipStream.Read(block, 0, block.Length);
                if (bytesRead <= 0)
                    break;
                else
                    outBuffer.Write(block, 0, bytesRead);
            }
            compressedzipStream.Close();
            return outBuffer.ToArray();
        }

**Comment by Dams591** [comment]
Hey @jol5  (and others)

I've a used a different approach since I'm using WCF and not asp.net, I'm not encoding it to base64 like you did but I'm simply sending a gzip of my stringified json

`data = JSON.stringify(data);
 data = pako.gzip(data);`  

Obviouly setting Content-Encoding to 'gzip'

And inside my WCF Application_BeginRequest here's what I'm doing

` If HttpContext.Current.Request.Headers("Content-Encoding") = "gzip" Then

                HttpContext.Current.Request.Filter = New GZipStream(Context.Request.Filter, CompressionMode.Decompress)

                ' Change the content length property to actual content lenght once decompressed.
                Dim contentLengthProperty = GetType(HttpRequest).GetField("_contentLength", BindingFlags.NonPublic Or BindingFlags.Instance)
                contentLengthProperty.SetValue(HttpContext.Current.Request, CType(HttpContext.Current.Request.InputStream.Length, Int32))

            End If`
