### ISSUE TITLE
PAKO and MINGW return different gzip outputs from the same input

### ISSUE THREAD

**Issue by CubeBR** [nodeca/pako#181]
Hi, using the same data as input, pako and [mingw](http://www.mingw.org/)'s gzip commands return different outputs, as shown below:

<img src="https://i.imgur.com/bFqyXAT.png"></img>

The input is this file:
<img src="https://i.imgur.com/qIlzbN0.png"></img>

Is there a reason for this to happen?

functions I used:
**pako**
`pako.gzip(input);`
**mingw**
`gzip < input.oct > input.gz`

if I decompress the file generated by pako using the gunzip command in mingw, I get the original "raw" file without problems...

I really don't want to bother you all with "third-party issues", but it turns out that with mingw I can compress and use the result in other applications without problems, but with pako I'm not that lucky... 

I think it is worth informing that I'm passing the pako output through a 'blob' to make it available as a download for the user, and i'm using the "application/gzip" mime type.

**Comment by puzrin** [comment]
There are lot of low-level deflate options - window size, compression level and so on. To compare binaries you should know those values.

Pako has tests, proving results are the same with zlib, that's enougth https://github.com/nodeca/pako/blob/master/test/deflate.js.

**Comment by CubeBR** [comment]
Thanks for the info, I thought that these settings were something "standardized", since the file generated by mingw works in any other application that I test...

According to [this website](http://www.gnu.org/software/gzip/manual/gzip.html#Sample), it uses the -6 compression level by default:
<img src="https://i.imgur.com/SslglRl.png"></img>

I don't know much about it, but I wasn't able to set -6 as level.
Could you explain to a layman like me which way to go to get equal outputs? :D

```
input = "4f43 5441 1d00 0000 2400 0000 0004 0000 0200 0000 0000 0000 0000 0000 0000 0000 0200 0000 0206 0073 6b79 626f 780e 0073 6b79 626f 7865 732f 7768 6974 6502 0800 6d61 7074 6974 6c65 1900 4f47 5a20 4564 6974 6f72 2066 6972 7374 2065 7665 7220 6d61 7003 6670 7300 0000 0000 0500 0200 0400 0300 0500 0700 0000 0044 0000 0044 0000 0044 0000 0000 0000 00ff 0000 0500 0000 0544 0000 0544 0000 0044 6e00 3200 0000 0000 0000 0200 0207 0007 0007 0001 0001 0001 0000 0202 0003 0004 0005 0006 0007 0000 0202 0003 0004 0005 0006 0007 0000 0202 0003 0004 0005 0006 0007 0000 0200 0000 0000 0007 0000 0000 0000 0100 0000 0000 0000 0000 0000 0000 0100 0000 0000 0000 0000 0000 0000 0100 0000 0000 0000 0000 0000 0000"

pako.deflate(input, { level: -6 });
```

**Comment by CubeBR** [comment]
Ok, thanks for the info, but what are the default options that zlib uses?
Is there a special reason why pako's default options are not the same as zlib's?

**Comment by puzrin** [comment]
There is no such term as "zlib defaults". You need to look concrete app code.

**Comment by CubeBR** [comment]
Oh sorry, I think i'm misunderstanding many things here...
Pako is a zlib port, this means that the zlib compression/decompression commands that I use on the command line were ported to javascript, right?

My only goal is to have the same function as the command `gzip < input.txt > output.gz ` in the browser, the "zlib defaults" I meant are about the values ​​mentioned [here](https://www.zlib.net/manual.html)...

I'm not arguing that pako doesn't work, the generated file is a valid gzip, and when unzipped it returns my original file without problems, but it just doesn't compress in the same way that zlib does by default...

**Comment by zt5** [comment]
一样的错误 
pako.deflate(data, {to: 'string'})
但是添加了raw参数就是正确的
pako.deflate(data, {to: 'string',raw:true})

**Comment by CubeBR** [comment]
So, it turns out that the inputs I was using were not exactly the same, my fault. The confusion occurred because, for one of the inputs, I was using plain text structured as hexadecimal (with space characters for easy viewing), and the other was a file encoded correctly as hexadecimal, this was obviously affecting the pako output...
