### ISSUE TITLE
How to get original string compressed in SQL server

### ISSUE THREAD

**Issue by Behnam1369** [nodeca/pako#183]
I compressed string in sql server: 
`select compress('this is just a sample string')`
the result was this: 
`0x1F8B08000000000004002BC9C82C5600A2ACD2E212854485E2C4DC829C5485E292A2CCBC7400206D53921C000000`

How can I get original string in javascript using pako.js?

**Comment by puzrin** [comment]
Sorry, this question is out of project scope.

**Comment by Behnam1369** [comment]
why is it out of project scope?
You mean I can't do this using Pako?

**Comment by Behnam1369** [comment]
It's some how like this issue:
[https://github.com/nodeca/pako/issues/64](url)

**Comment by puzrin** [comment]
Sorry, no resources to help with generic programming questions and questions about third party software. Such tickets are closed to keep tracker clean. Only tickets about bugs are accepted. Pako is almost presize zlib port.
