### ISSUE TITLE
[FYI] documentation clarity/simpler interface for binary inflation

### ISSUE THREAD

**Issue by splace** [nodeca/pako#184]
i spent some time trying to inflate a compressed binary file.

i took this from the docs....

```
      ungzip(data[, options])  Uint8Array|Array|String
```
to mean i could do this...

`decompressed-data=new Float32Array( Ungzip(compressed-data))
`

that didn't work, eventually figured i had to do this...

`decompressed-data=new Float32Array( Ungzip(compressed-data).buffer)
`

ideally the original use would have worked, it would be a simpler, neater, interface, or if not possible then highlighted in the docs that whats returned isn't actually an 'real' ArrayBuffer.

**Comment by alexeyten** [comment]
This is just how typed arrays work in js.

And documentation clearly states `Uint8Array`, not an ArrayBuffer.

**Comment by puzrin** [comment]
As been said above, seems nothing to fix. Or suggest a concrete change.

**Comment by splace** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array


> Uint8Array.prototype.buffer Read only
>     Returns the ArrayBuffer referenced by the Uint8Array Fixed at construction time and thus read only.
> 

your returned object has a property 'buffer', an ArrayBuffer, but (see above) Uint8Array's require it be a property of an objects prototype, this explains the issue and means what you return isn't, as stated in the docs, an Uint8Array.

concrete change; move buffer to prototype or fix the docs.

**Comment by puzrin** [comment]
Please, inspect the real code. It uses `Uint8Array` if available (~ always).

**Comment by alexeyten** [comment]
> your returned object has a property 'buffer', an ArrayBuffer, but (see above) Uint8Array's require it be a property of an objects prototype

Nope. Please, familiarize yourself with JS and in particular with prototypes.
