### ISSUE TITLE
Missing data while diflate

### ISSUE THREAD

**Issue by biju-ps** [nodeca/pako#185]
Hi I am porting Android version of this [App ](https://github.com/dimagi/AadharUID/blob/master/app/src/main/java/org/commcarehq/aadharuid/ScanResult.java)to C#  and JS. My C# implementation is over. I am using pack to decompress the compressed bytes. While using pako , I am losing 4 characters after each special character (�) in the result 

please  have a look at this jsfiddle
http://jsfiddle.net/eprk23vo/6/     

Please refer  my c# implementation 
https://dotnetfiddle.net/3yWap1

output   in c#. 
> 3�169020200216035132173�Austin Paul�18-08-1993�....

output in pako 

>  3�0200216035132173�n Paul�-1993�....

In pako,�**Austin Paul**� became �**n Paul**� .. Anything I missed. Please help

**Comment by puzrin** [comment]
Sorry, can't help with debugging your code. I'd suggest use tests as examples.
