### ISSUE TITLE
How to unzip pako compressed data in golang?

### ISSUE THREAD

**Issue by swinsome** [nodeca/pako#186]
Brower client send pako compressed data to goalng server with grpc-web.The server can not unzip the date.Golang report "header error "。
client demo code:
    s="this is a demo test!"
    str=s.repeat(200)
    dsts=pako.gzip(str,{to:'string'})

golang code:
                        b := bytes.NewReader([]byte(data))
			r,err := zlib.NewReader(b)
			if err!=nil{
				fmt.Println(err)//"header error"
			}else{
				io.Copy(os.Stdout, r)
			}

**Comment by puzrin** [comment]
Can't help with other languages, sorry. Paco is binary compaoble with zlib. I doubt you should use "to: string" in compressor.

**Comment by rk185151** [comment]
You almost had it, just missed decoding bas64 - please see following go code seems to work
```go
       sdata, _ := base64.StdEncoding.DecodeString(data)
	b := bytes.NewReader([]byte(sdata))
	r, err := zlib.NewReader(b)
	if err != nil {
		fmt.Println(err) //"header error"
	} else {
		io.Copy(os.Stdout, r)
		r.Close()
	}
```

**Comment by haiqun** [comment]
> 

Well, that's not gonna work

**Comment by yakumioto** [comment]
> You almost had it, just missed decoding base64 - please see following go code seems to work
> 
> ```go
>        sdata, _ := base64.StdEncoding.DecodeString(data)
> 	b := bytes.NewReader([]byte(sdata))
> 	r, err := zlib.NewReader(b)
> 	if err != nil {
> 		fmt.Println(err) //"header error"
> 	} else {
> 		io.Copy(os.Stdout, r)
> 		r.Close()
> 	}
> ```

Use `base64.RawURLEncoding.DecodeString(data)`
