### ISSUE TITLE
cannot resolve './common'

### ISSUE THREAD

**Issue by leidegre** [nodeca/pako#188]
What is this? Why does it end up in the dist? I'm trying to bundle pako because it's used by another library but this import isn't found.

https://github.com/nodeca/pako/blob/master/dist/pako_deflate.js#L113

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/blob/master/dist/pako_deflate.js#L297 everyting is as expected. Those calls are shimmed. Please, refer to `browserify` docs for how it works.

If you think file is broken - please provide a minimal demo how to reproduce.

**Comment by leidegre** [comment]
I just realized, thanks for the quick reply!
