### ISSUE TITLE
How to work with strings with Pako 2.0?

### ISSUE THREAD

**Issue by saneef** [nodeca/pako#197]
Since the support for string is dropped on 2.0

What would be ideal way to rewrite this sample code on string usage:

```javascript
const pako = require('pako');

const test = { my: 'super', puper: [456, 567], awesome: 'pako' };

const compressed = pako.deflate(JSON.stringify(test));

const restored = JSON.parse(pako.inflate(compressed, { to: 'string' }));
```

**Comment by puzrin** [comment]
This all still works. See example.

I removed only "binary strings" support, when deflate output is string. That could be useful only for IE6/7.
