### ISSUE TITLE
SyntaxError: Unexpected end of JSON input after pako.inflate

### ISSUE THREAD

**Issue by meold** [nodeca/pako#198]
I use express backend and send data like this:

```
const data = pako.deflate(JSON.stringify(myJsonData), { to: 'string' });

res.json({ success: true, data });
```

And in frontend part:
```
const data = JSON.parse(pako.inflate(resultFromBackend, { to: 'string' }));
```

All is OK in pako v1.0.11

But in v2.0.0 I have the error **Unexpected end of JSON input** in the frontend part.

**Comment by puzrin** [comment]
2.0 does not supports binstring output for deflate, it's output is Uint8Array. You need to adjust your data transfer or convert Uint8Array to string manually.

Also note:

- it's better use zlib in node
- express should have compression plugins for replies, no need for custom machinery.
