### ISSUE TITLE
Unexpected token 'export': export default pako;

### ISSUE THREAD

**Issue by IgorNovozhilov** [nodeca/pako#199]
## environment

Node  v14.15.1
pako v2.0.0

## usage

node test.js

```js
import pako from 'pako'
```

## output

```
(node:12519) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/***/development/***/node_modules/pako/dist/pako.esm.js:6671
export default pako;
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by puzrin** [comment]
released 2.0.1

**Comment by puzrin** [comment]
Do you know howto foce rollup geterae esm exports for all functions, instead of default pako https://github.com/nodeca/pako/blob/master/dist/pako.esm.mjs#L6671 ?

Seems it produced result not as i expected.

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/commit/d0382badcc60e1c08b51ea0aec10528e8565e1b6 solved

**Comment by IgorNovozhilov** [comment]
> solved

:+1:
