### ISSUE TITLE
Minified build in npm package makes auditing harder

### ISSUE THREAD

**Issue by joepie91** [nodeca/pako#204]
Hi,

pako currently includes a minified build in its package on npm, but unfortunately this is making dependency auditing quite a bit harder; in addition to a human-readable version, a minified version now also needs to be audited and/or reproduced (which has its own toolchain trust issues).

I've written a bit more about this topic (and why minified builds are not useful on npm) [here](https://gist.github.com/joepie91/04cc8329df231ea3e262dffe3d41f848) -- I'd like to request removing it from the npm package :)

**Comment by puzrin** [comment]
Minified build was requested for jsdelivr cdn. It will not be removed. Just use ordinary one.
