### ISSUE TITLE
Ungzip on 2.0.2 broken when it works fine on 1.0.11

### ISSUE THREAD

**Issue by joelpoloney** [nodeca/pako#205]
Relevant fiddle: https://jsfiddle.net/mg76vhps/2/

Notice how when it runs, the console spits out `"unknown compression method"`. However, if I change the import from cloudflare to `1.0.11` instead of `2.0.2`, no error occurs and it works just fine.

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/blob/master/CHANGELOG.md#changed-1

IMO when you upgrade major version, it's logical to inspect changelog for breaking changes :). There been said explicit, 2.x dropped support of binary String-s and Array-s. You should provide compressed data as Uin8Array instead.

**Comment by joelpoloney** [comment]
Cool. Next time you can provide the info without being a jerk about it. Thanks for the update.

**Comment by puzrin** [comment]
Unfortunately, due time constraints, free support is limited and not includes using tracker for basic programming questions. But i can give you patreon or opencollective links, if you ever decide to motivate my patience. Good luck!
