### ISSUE TITLE
Restore deflate `{ to: 'string' }` option on version 2

### ISSUE THREAD

**Issue by Mogztter** [nodeca/pako#206]
Hello,

I'm currently using the following code with Pako 1.0.11:

```js
pako.deflate(textEncode(source), { level: 9, to: 'string' })
```

I noticed that the option `{ to: 'string' }` is not supported anymore on `deflate` (but still supported on `inflate`). The code to convert a buffer to a String is also still available at:

https://github.com/nodeca/pako/blob/45cce9f4d67dcd446e753a70ec31a56955ac20fc/lib/utils/strings.js#L99

So I'm wondering if this change is intended? And if by any chance we could restore this feature on deflate?

I can open a pull request with this change but first I want to make sure that we are in agreement :smile: 

Thanks!

**Comment by puzrin** [comment]
Those are different "strings". Deflate output an inflate input are BINARY data - drop of those in string form is intended. That existed only for ancient browsers without typed arrays support. Now that's not actual.

The rest is for utf16 <=> unicode conversion, and useful for easy text porocesing (for example, simple json pack).

---

So, quick answer is "no, `{ to: 'string' }` for deflate is not welcome"

**Comment by Mogztter** [comment]
Thanks for your quick reply.

> That existed only for ancient browsers without typed arrays support. Now that's not actual

Could you please confirm how a modern browser should convert the output of `deflate` to a string form?
I can see that Pako 1.0.11 was using `fromCharCode`:

https://github.com/nodeca/pako/blob/a718e4f6e5ce87b0964d8f84541d92a23263365b/lib/utils/strings.js#L85-L100

But maybe [`TextDecoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) is now the preferred way?

**Comment by puzrin** [comment]
> Could you please confirm how a modern browser should convert the output of deflate to a string form?

It should NOT do such thing. I can not imagine context, where such operation is required and valid. Of cause, i can not prohibit you do that, but IMO such questions are out of this package scope.

**Comment by Mogztter** [comment]
> It should NOT do such thing. I can not imagine context, where such operation is required and valid. 

PlantUML is using deflate to compress a diagram definition and then reencode in ASCII using a transformation close to base64.
For instance:

```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
@enduml
```

is encoded as: `Syp9J4vLqBLJSCfFib9mB2t9ICqhoKnEBCdCprC8IYqiJIqkuGBAAUW2rO0LOr5LN92VLvpA1G00`

<img src="https://www.plantuml.com/plantuml/svg/Syp9J4vLqBLJSCfFib9mB2t9ICqhoKnEBCdCprC8IYqiJIqkuGBAAUW2rO0LOr5LN92VLvpA1G00"/>

https://www.plantuml.com/plantuml/svg/Syp9J4vLqBLJSCfFib9mB2t9ICqhoKnEBCdCprC8IYqiJIqkuGBAAUW2rO0LOr5LN92VLvpA1G00

> Of cause, i can not prohibit you do that, but IMO such questions are out of this package scope.

Fair enough, even though it was somehow possible with version 1.x.
But I'm fine with implementing the logic on my side.

**Comment by puzrin** [comment]
https://stackoverflow.com/questions/12710001/how-to-convert-uint8-array-to-base64-encoded-string

**Comment by Mogztter** [comment]
@puzrin Thanks! :+1:

**Comment by puzrin** [comment]
Since you use custom base64-like encoder, it would be logical if it eats typed array directly. It needs bytes on input (to extract 6-bit sequense).

So yes, your task needs text output, but it does not needs deflate to binstring conversion.

---

Is `plantuml.com/plantuml/svg/` backend stable? Can it be used for direct image embed into document or cache / sandalone server should be used?

**Comment by Mogztter** [comment]
For reference, I also found https://github.com/beatgammit/base64-js which provides a function to convert a bytes array to base64: `fromByteArray`.
Though, I'm not sure if `String.fromCharCode` is actually enough in this case or if we need to use a more advanced implementation to handle multibytes characters?

> Is plantuml.com/plantuml/svg/ backend stable?
> Can it be used for direct image embed into document or cache / sandalone server should be used?

Yes I believe that plantuml.com is stable. Alternatively, you can use https://kroki.io which provides the same API.

**Comment by puzrin** [comment]
> Though, I'm not sure if `String.fromCharCode` is actually enough in this case or if we need to use a more advanced implementation to handle multibytes characters?

That's because you confuse "binary data" and "text data". Defleate output is binary data. Each item is "byte" (8 bits). It's technically impossible to have multibyte issues there.

**Comment by Mogztter** [comment]
> That's because you confuse "binary data" and "text data". Deflate output is binary data. Each item is "byte" (8 bits). It's technically impossible to have multibyte issues there.

I see, that makes sense :+1: 

> What you do now, is converting each byte into charcode, and then converting chacode back to byte in base64 encoder. 2 useless operations. May be you have some legacy stuff, and have to follow such logic (i don' know your details). But typed array can be consumed directly, doing everything more simple.

Oh right, I can produce a base64 string directly from the bytes array (produced by Pako deflate). I guess that's what Node.js is doing when using `buf.toString('base64')`.
So, `base64-js` should give me a direct conversion from bytes array to base64 string (it removes the extra step of converting the bytes array to string using `fromCharCode`). Did I get it right?

Many thanks for your guidance and clarification 🙌

**Comment by puzrin** [comment]
> So, `base64-js` should give me a direct conversion from bytes array to base64 string (it removes the extra step of converting the bytes array to string using `fromCharCode`). Did I get it right?

Exacly.

Or you can take this code https://gist.github.com/enepomnyaschih/72c423f727d395eeaa09697058238727#file-base64-js-L84-L104 and use your own mapping table. Then you will get what you need in single pass.

**Comment by barthuijgen** [comment]
Hi! I have the opposite problem as reported by this issue. Pako version `1.0.11` worked fine but version `2.x.x` fails to parse Factorio blueprint strings, a json string compressed, text encoded and then base64 encoded. The code would look like this
```
const compressed = atob(source.substring(1));
const encoded: any = pako.inflate(compressed);
const string = new TextDecoder("utf-8").decode(encoded);
const data = JSON.parse(string);
```
Sample string
```
0eNptjsEOgkAQQ/+l54UILKL7K8YYwIlOAgNhByMh+++yePHgsU372hVNN9M4sSjcCm4H8XCXFZ4fUnfR02UkOLBSDwOp+6i8EnVJ+ySvCAYsd3rDZeFqQKKsTF/MLpabzH1D0xb4CzAYB791Bol7Gycp0tJggTse0jJE6L7ufs4avGjyeyU/ZbY651VhbWVzG8IHG4NFbQ==
```
Is this still possible with Pako 2? because `pako.inflate()` is throwing an error now saying: "unknown compression method"

**Comment by puzrin** [comment]
@barthuijgen `atob()` returns string, but `pako.inflate()` in 2.0 requires `Uint8Array` (other types are not supported).

**Comment by barthuijgen** [comment]
@puzrin Thanks for the quick reply :) so if I understand correctly you're saying pako 2.0 dropped support for this use case compared to 1.0.11? Because I did try converting the string to a Uint8Array myself, but pako still errored with "unknown compression method"

**Comment by puzrin** [comment]
> Because I did try converting the string to a Uint8Array myself, but pako still errored with "unknown compression method"

I don't believe you did it right :). Just make sure `inflate` get exactly the same `Uint8Array` as produced by `deflate`, and it will work, i'm sure 100%.

**Comment by barthuijgen** [comment]
The problem with that is that i don't produce the compressed strings myself. it's a game that does it and I'm making a website to handle thier exported string. It's quite popular and I've seen pako used for it in multiple other projects as well.

Again pako 1.0.11 did this perfectly, can you refer me to the part of the code that was taken out so I can implement it myself?

**Comment by ByordiShilpa** [comment]
"It should NOT do such thing. I can not imagine context, where such operation is required and valid. Of cause, i can not prohibit you do that, but IMO such questions are out of this package scope."

MediaWiki used the pako base64 output to send VisualEditor HTML back to the server. (which makes sense as uploads, unlike downloads, don't support gzip)

Alternative uses are to store preferences (which can't be some numbered array) or to store information in localStorage. (which can't be some numbered array) Frankly, I can't imagine context in which numbered arrays would be a useful output.

Converting these numbered arrays to base64-encodable strings is a pain as base64 only allows 1 byte per character. I tried out a bunch of stuff, but this is way too complicated and will not contribute to code I can really maintain.

I believe this change splits the pako userbase into three groups:
1. "I will never update pako again and stick with 1.11"
2. "Why are you forcing me to add code to make this work again?" (https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/heads/master/resources/src/mediawiki.deflate/mw.deflate.js)
3. "Let's find an alternative to pako."

It's your project and you seem to have made your decision. But I wish you hadn't just dropped a feature that -I'm guessing- 90%+ of your userbase relies on without providing a clear transition guide.

On  the main page there is an example "Sometime you can wish to work with strings. For example, to send stringified objects to server." but this example generates a Uint8Array which you can't send to a server.

**Comment by puzrin** [comment]
1. AFAIK, all modern browsers support typed arrays send
2. There is example https://github.com/nodeca/pako/tree/master/examples
3. You still can encode/decode typed arrays to base64, if you wish, this is trivial, and, IMHO, a bit out of this project csope.

**Comment by ByordiShilpa** [comment]
1. That's not my main concern. (depending on how old browsers have to be, I may not care at all)
2. Within MediaWiki there is nothing I can do with that. When storing data in localStorage, that won't work. If I need users to be able to copy/paste data for whatever reason, that won't work. If I need to pass data as HTTP GET arguments, that won't work.
3. I don't doubt it's trivial for you, but not everyone is an expert on array to base64 encoding/decoding. I know, because I had it set up for a while. It seemed to be working (output in tests was even identical to pako 1.x), but now I found out data has been getting corrupted/lost for months on random occasions.

If there are some freely licensed functions that can do this reliably (preferably resulting in the same input/output as pako 1.x) it would be very nice to link that in a prominent place for pako 1.x users so they can safely transition to 2.x. But it's your project.

**Comment by latobibor** [comment]
Hi @puzrin!

   I just wish to expand on the usage of this package and why plain old legacy `string` can be extremely useful. I need to work with `react-native` and store data into `AsyncStorage` . The catch is: the storage has a [2Mb write/read limit](https://react-native-async-storage.github.io/async-storage/docs/limits) and it only accepts [_strings_](https://react-native-async-storage.github.io/async-storage/docs/usage).
   
 The type of material (hard to chop up geodata) I need to work with can scale up to 10 Mb. This package shrank our 10Mb file to 250Kb. Even with the "useless" steps above it works perfectly for our use case - however it is clunky compared to just dropping in an elegant option. The JS world is no longer just browsers and node.

**Comment by nelsonjchen** [comment]
For those of us who are using pako between services and can't upgrade everything at once, temporarily vendoring select functions in the older version and using them for pako 2 inputs from pako 1 output strings seems to work for me. 

https://github.com/nodeca/pako/blob/1.0.11/lib/utils/strings.js#L110 

Just something to note for those of us in the midst of migrating.

**Comment by kflorence** [comment]
Just because an example seems hard to find and I see questions all over the place about it, here is an easy way to encode/decode to base64 with `pako`:

```javascript
import pako from 'pako'

function base64decode (string) {
  return new TextDecoder().decode(pako.inflate(Uint8Array.from(window.atob(string), (c) => c.codePointAt(0))))
}

export function base64encode (string) {
  return window.btoa(String.fromCodePoint(...pako.deflate(new TextEncoder().encode(string))))
}
```

An example (with unicode):

```javascript
base64encode('test 🦄') // => 'eJwrSS0uUfgwf1kLABUvBJo='
base64decode('eJwrSS0uUfgwf1kLABUvBJo=') // => 'test 🦄'
```

**Comment by latobibor** [comment]
> ```js
> base64encode('test 🦄') // => 'eJwrSS0uUfgwf1kLABUvBJo='
> base64decode('eJwrSS0uUfgwf1kLABUvBJo=') // => 'test 🦄'
> ```

It's all good, but the resulting string is much, much longer than the original was. Maybe because the example string is so short. My point is, that probably this is not so efficient as was the original `{ to: 'string' }` option would produce.
