### ISSUE TITLE
Unzip of gzip fails on v2 (fine with v1.0.11)

### ISSUE THREAD

**Issue by freemaths** [nodeca/pako#207]
Not urgent as v1.0.11 works fine.

Object zipped in php on server with: 
base64_encode(gzcompress(json_encode($json)))
Now fails to inflate with:
JSON.parse(pako.inflate(atob(data), { to: 'string' }))
(complains about unknown compression)

Let me know if you would like any additional debug/information.

**Comment by puzrin** [comment]
atob returns string, inflate needs typed array on input. See changelog, binary strings support was dropped.

**Comment by freemaths** [comment]
Is the following from the top level readme still correct?
An example of how best to send json data to and from server would be helpful.
===============================================================
Sometime you can wish to work with strings. For example, to send stringified objects to server. Pako's deflate detects input data type, and automatically recode strings to utf-8 prior to compress. Inflate has special option, to say compressed data has utf-8 encoding and should be recoded to javascript's utf-16.

const pako = require('pako');

const test = { my: 'super', puper: [456, 567], awesome: 'pako' };

const compressed = pako.deflate(JSON.stringify(test));

const restored = JSON.parse(pako.inflate(compressed, { to: 'string' }));

**Comment by puzrin** [comment]
Yes, example is valid. Problem is in your atob. Convert it's output to Uin8Array, and inflate will work.
