### ISSUE TITLE
About "Removed binary strings support"

### ISSUE THREAD

**Issue by hopefuture** [nodeca/pako#209]
I find that "Removed binary strings support".

In "pako 1.x", the following code can returns the compressed value.
but in "pako 2.x", it return the different compressed value.
```javascript
export function gzipCompress (text: string) {
  const gzip = pako.gzip(text, { to: 'string' });
  return btoa(gzip);
}
```

How to implement it in the new version(2.x), thank you!

**Comment by hopefuture** [comment]
Can you provide a code implementation in pako 2.x? Thank you！

**Comment by puzrin** [comment]
`gzip = pako.gzip(text)` then https://stackoverflow.com/questions/9267899/arraybuffer-to-base64-encoded-string

See https://github.com/nodeca/pako/issues/206
