### ISSUE TITLE
Unzip of Json array object is slow

### ISSUE THREAD

**Issue by multiaki** [nodeca/pako#210]
I have a 200k json object (~68million chars). Pako level 6 compression take 9 seconds to unzip. Level 1 takes 5 seconds to unzip. 
Here is my code:
zip: pako.deflate(JSON.stringify(jsonArrayObj), {to: "string", level: 6})
unzipp: pako.inflate(jsonArrayObj, {to: "string", level: 6}) - This takes at least 9 seconds

jsonArrayObj = [{id: 1, title: "My title"}] (length 200 000, chars 68 million)
I appreciate any suggestions. Please share some articles or examples. 

Thanks

**Comment by puzrin** [comment]
deflate does not accepts  `{ to }` and inflate requires typed array. Your example is invalid.
