### ISSUE TITLE
How to import only the "inflate" function.

### ISSUE THREAD

**Issue by Directory** [nodeca/pako#213]
Im using this with webpack and webpack bundle analyzer to see the size. right now im using pako with `const pako = require('pako');` and when building it takes up an entire 40kb of space. im only using the inflate function. im trying to figure out how to import only that much. i tried `import { inflate } from 'pako';` and although it did build nothing changed its still the entire 40kb.

**Comment by puzrin** [comment]
The most "stupid" approach is to require `pako/lib/inflate.js` or `pako/dist/...`

But, as far as i understand, tree shaking works only with "import". I have no idea why it doesn't happen in your case.

**Comment by Directory** [comment]
im going to assume this is just a limitation on the librarys part since the devs probably did not expect for it to be used in a frontend use that needs tree shaking. also i tried `const inflate = require('pako/lib/inflate.js')` and got `Module not found: Error: Package path ./lib/inflate.js is not exported from package` so yea the functions arent `exported` to begin with.

i am going to look into alternative compression formats with alternative librarys that implement them.

**Comment by puzrin** [comment]
> im going to assume this is just a limitation on the librarys part since the devs probably did not expect for it to be used in a frontend use that needs tree shaking.

You can assume anything, but:

- tree shaking works indepenent on your assumptions.
- it's not good idea to waste developper's time for reading all assumtions you can imagine.

>  so yea the functions arent `exported` to begin with.

https://github.com/nodeca/pako/blob/master/package.json#L33-L34

those are exported an work as expected.

> i am going to look into alternative compression formats with alternative librarys that implement them.

This info would be more appropriate in you personal log, not in this tracker.

**Comment by lmeyerov** [comment]
If it helps for docs / googling, `import { deflate } from 'pako/lib/deflate.js';` (note the `.js` suffix) worked with webpack, knocking off ~17KB uncompressed.
