### ISSUE TITLE
deflating strings results in uintArray instead of decompressed data

### ISSUE THREAD

**Issue by hrigner** [nodeca/pako#214]
When using pako 1.0.11, `pako.deflate(JSON.stringify(myJsonObject))` results in compressed data, but when bumping to pako 2.x, the `pako.deflate(JSON.stringify(myJsonObject))` results in a uintArray, which is not compressed data.

Am I supposed to do anything differently with v2?

**Comment by puzrin** [comment]
Result of `deflate` is `Uint8Array`, i see no problem.

**Comment by hrigner** [comment]
The deflate function in v2.x does not give the same output as the deflate function in v1.0.11 .. 
```

```
results in 
```Uint8Array(17) [
  120, 156,  99, 100,  98, 102,
   97, 101,  99, 231, 224,   4,
    0,   0, 174,   0,  46
]

**Comment by hrigner** [comment]
Using v1.0.11
```
const data = { test: { myobject: { t: 1}}};
console.log(pako.deflate(JSON.stringify(data), { to: 'string'}));
```
results in
```
x«V*I-.Q²ªVÊ­ÌOÊJM³amm-Z
%
```
which when using a large JSON object gives me a significant smaller size. 

The same code gives me this in v2.x
```
Uint8Array(32) [
  120, 156, 171, 86,  42,  73,  45, 46,
   81, 178, 170, 86, 202, 173, 204, 79,
  202,  74,  77,  6, 179, 129, 132, 97,
  109, 109,  45,  0, 153,  90,  10, 37
]
```
and when using my large JSON object my data doesn't get any smaller.

What am I doing wrong?

**Comment by puzrin** [comment]
2.0 dropped support of `{ to: 'string' }` for deflate. That's said in changelog https://github.com/nodeca/pako/blob/master/CHANGELOG.md#changed-1 `Removed binary strings and Array support.`

Also see https://github.com/nodeca/pako/issues/206

**Comment by hrigner** [comment]
Thanks for pointing me in the right direction! I now have it working as expected! 🎉
