### ISSUE TITLE
Majority of files fails to inflate with error -3 invalid distance too far back

### ISSUE THREAD

**Issue by exander77** [nodeca/pako#216]
Around 80% of inflates fails with this error. Inflate created without any options.

**Comment by exander77** [comment]
![Uploading Screenshot_2021-01-22_22-01-05.png…]()

**Comment by puzrin** [comment]
This does not says to me anything. Please, provide reproducible sample to reopen. And make sure you do not duplicate existing issues.

**Comment by exander77** [comment]
It is most likely a duplicate as above, I haven't produced the files, I have just taken files that were intended for my use.

Seems like blocked BGZF: https://github.com/nodeca/pako/issues/139

But around 80% of all files I have tested are of this type.
