### ISSUE TITLE
No files are downloaded when installing `pako`

### ISSUE THREAD

**Issue by ArenaGrenade** [nodeca/pako#217]
I use `yarn` as my package manager and I have tried out the following commands
```
yarn add pako
```
```
yarn add git+https://github.com/nodeca/pako.git
```
I have also given `npm install pako` a try, but to no avail.

All of them gave no errors and they both do put up an entry in `package.json`. Could it be possible that the current version of the package has some issues? I do not understand.

**Comment by puzrin** [comment]
`npm i pako` works for me.

Closing as not specific for this package.

**Comment by ArenaGrenade** [comment]
No? Every other package works on me except pako.

**Comment by puzrin** [comment]
See download stats @ npm. It's impossible to have broken release without lot of reports with such volumes.

I beleive you have problem, but that's not enough to participate, sorry.
