### ISSUE TITLE
Script to create dist/ folder

### ISSUE THREAD

**Issue by clashman** [nodeca/pako#223]
I could not find how the files in dist/ are generated. It would be great if the script could be included in this repo.

Use case: I would like to regenerate pako_deflate.min.js with an exported crc function.

Why is this function not exported?

**Comment by puzrin** [comment]
>  could not find how the files in dist/ are generated.

https://github.com/nodeca/pako/blob/master/package.json#L42

`npm run build`

> Why is this function not exported?

Wrong question in wrong place. We do not export anything just for fun. You can also require file by path.
