### ISSUE TITLE
Uncaught incorrect header check

### ISSUE THREAD

**Issue by j2l** [nodeca/pako#224]
Hello,
Using svelte, I can:
```
import {deflate, inflate} from "pako"
let test = [{"key":"value"}]
localStorage.setItem("test", deflate(JSON.stringify(test)))
let testreturn = JSON.parse(inflate(localStorage.getItem("test"), { to: 'string' }))
```
Svelte needs module.exports, hence the import.
In the local store, it correctly writes the values `120,156,139,174,86,202,78,173,84,178,82,42,75,204,41,77,85,170,141,5,0,51,214,5,217`
but when inflating I get: `Uncaught incorrect header check`
What do I do wrong? 
Thanks

**Comment by alexeyten** [comment]
https://nodeca.github.io/pako/#inflate

`inflate` requires data to be `UInt8Array` but you pass it a `string` (because localstorage can only contain strings)

**Comment by alexeyten** [comment]
BTW, I'm not sure if it's a good idea to deflate something just to store it in a localstorage in the most ineffective way.
You should consider to use something like this https://stackoverflow.com/a/52420482/1016033

**Comment by j2l** [comment]
Thank you very much Alexey!
I'm learning :)

**Comment by j2l** [comment]
BTW, I was using the example from the README page, above the https://github.com/nodeca/pako#notes
