### ISSUE TITLE
changes from 1.0.11 to 2.0.x?

### ISSUE THREAD

**Issue by happy15** [nodeca/pako#227]
Hi there,

we are now using pako 1.0.11 and consider upgrading to 2.0.x. However, I cannot find release notes describing the differences between 1.0.11 and 2.0.x. 

Can I just bindly upgrade to 2.0.x?

And thanks, pako is a great lib.  👏

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/blob/master/CHANGELOG.md#200---2020-11-17

Anything wrong with it?

In short: if you did not used `{ to: string }` for deflate, usually upgrade should be ok. Also see closed issues with similar questions.
