### ISSUE TITLE
Use slice instead of subarray?

### ISSUE THREAD

**Issue by huachaoliu** [nodeca/pako#229]
```
const buf2binstring = (buf, len) => {
  // On Chrome, the arguments in a function call that are allowed is `65534`.
  // If the length of the buffer is smaller than that, we can use this optimization,
  // otherwise we will take a slower path.
  if (len < 65534) {
    if (buf.subarray && STR_APPLY_UIA_OK) {
      return String.fromCharCode.apply(null, buf.length === len ? buf : buf.subarray(0, len));
    }
  }
 ...
}
```
Can I use slice instead of subarray? I notice that buf here is an array type.

**Comment by huachaoliu** [comment]
When the amount of data is too large, reduce the number of calls to ```string.fromCharCode``` to reduce memory overhead.

**Comment by puzrin** [comment]
Please, avoid generic programming questions/talks. If you have proposals, provide appropriate metrics - benchmark, memory profile and so on.
