### ISSUE TITLE
no error or return for pako inflate?

### ISSUE THREAD

**Issue by DevinBayly** [nodeca/pako#231]
Hi there,

I'm trying to use pako for clientside decompression but for some reason the code doesn't return the decompressed Uint8Array when using the `inflate` method. I also don't see an error getting caught for some reason?

Any help would be great!

https://pakotest.baylyd.repl.co

**Comment by puzrin** [comment]
Sorry, can't debug code for you. See examples & tests as start point.

**Comment by rlidwka** [comment]
@DevinBayly can you please show exactly how that file (data.bin) is generated, with what software and what compression options?

**Comment by DevinBayly** [comment]
Hi, sure.

The original usecase is to uncompress the compressed part of a minecraft region file. The compression scheme information was listed here https://minecraft.fandom.com/wiki/Region_file_format#Chunk_Data.

The processing that I did was on an observablehq notebook here. https://observablehq.com/d/d9e3e41da8a581c3

I mention in there that both minizlib works at uncompressing the data and in a roundabout way so does https://nodeca.github.io/pako/#Inflate.new if I look at the `strm.output` attribute. None of the straightforward examples on the documentation seem to work with this particular set of data but there also isn't an error to catch.

Thanks for revisiting this!

**Comment by rlidwka** [comment]
At the very end of your data there is an extra byte (with value 59).

If you run `pako.inflate(intarray.slice(0, -1))` instead of `pako.inflate(intarray)`, you'll see that it works just fine.

The question is: where does this extra byte come from in your binary file? What software has generated it and why?

**Comment by rlidwka** [comment]
Reproduction sample:

```js
let zlib = require('zlib');
let pako = require('pako');

let sample = zlib.deflateSync(Buffer.from('foobar'));
let sample2 = Buffer.concat([ sample, Buffer.from([ 1 ]) ]);

console.log('zlib sample 1', zlib.inflateSync(sample));
// outputs <Buffer 66 6f 6f 62 61 72>

console.log('pako sample 1', pako.inflate(sample));
// outputs Uint8Array(6) [ 102, 111, 111, 98, 97, 114 ]

console.log('zlib sample 2', zlib.inflateSync(sample2));
// outputs <Buffer 66 6f 6f 62 61 72>

console.log('pako sample 2', pako.inflate(sample2));
// outputs undefined
```

**Comment by DevinBayly** [comment]
really? one extra byte made all the difference I suppose. 

The length of the compressed data was something that I calculated using the first 4 bytes of the chunk header pasted again here 
![image](https://user-images.githubusercontent.com/11687631/128086827-7a224d0c-47fe-4893-9191-0e513bf35ba1.png) but it's entirely on me that there's an off by one error in calculating the length of the compressed data. 

So in a sense the extra byte in the binary file comes from me supplying one too many bytes probably by computing the length in bytes of the compressed data wrong with this code 

```
function compute_chunk_size(hdr) {
  return hdr.reduce((acc, cur, i) => {
    // the header is 4 bytes so 0-3 are the i's
    return acc + (cur << (8 * (3 - i)));
  }, 0);
}
```
supplying the `[0,0,15,131]` as the hdr parameter above

I guess I shouldn't expect pako to speak up in cases like this with an error thrown though.
