### ISSUE TITLE
Closed #239 -- Difference between pako.gzip/deflateRaw and the PHP gzip funcs..

### ISSUE THREAD

**Issue by deehill** [nodeca/pako#240]
Hi.

Not to be a bother. But you guys closed the #239, as you said transfer issues aren't handled. Fair enough.

However, my real issue is why there appears to be a difference between the pako gzip/deflateRaw and the PHP functions. This is the cruz of my concern. And as I've seen, there have been others over the years who've had the same question/concern.

Thanks

ps. much appreciation for the work you guys do!

**Comment by puzrin** [comment]
Please, stop create issues about generic programming questions, this tracker is not suited for such demands. Use StackOverflow and similar sites.
