### ISSUE TITLE
Unable to decompress gzip response

### ISSUE THREAD

**Issue by qnxdev** [nodeca/pako#246]
Trying to decompress gzip response from this websocket but it always give errors

wss://api.cointiger.com/exchange-market/ws

What should be the correct format?
This is the WS related doc.

It says response is gzipped
https://github.com/cointiger/api-docs-en/wiki/Public-Request-And-Subscription-Instructions

**Comment by puzrin** [comment]
Sorry, can't help with generic programming questions. See tests, this lib is checked against binary compatibility with `zlib`, but i'm not responsible for how do you use it.
