### ISSUE TITLE
Problem with ES6 import n MS Edge

### ISSUE THREAD

**Issue by bernyspeedy** [nodeca/pako#248]
Dear Sirs,

I would like to use pako in the Edge Browser as ECMASCRIPT 6 import:

import * as pako from 'http://localhost/pako.js';
...
let zlibstream = new Uint8Array(result[3]);

let XRefStream = pako.inflate(zlibstream);

===
in the Developer view of the edge Browser,
"Uncaught TypeError: pako.inflate is not a function"
is displayed.

It would be very kind, if you could give me a hint, if I made a mistake in the usage, or I had a misunderstanding and ES6 moule support is not intended.

Thanks a lot and kind regards,

Bernhard

**Comment by puzrin** [comment]
If you select path manually, use appropriate file https://github.com/nodeca/pako/blob/master/package.json#L29
