### ISSUE TITLE
"invalid distance too far back" with 2.0?

### ISSUE THREAD

**Issue by cmdcolin** [nodeca/pako#250]
using pako 2.0.4 on a file produces an error on a file that appears to work fine in 1.0

I tested this with `node index.js` with node v16.13.2 for ref

```
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^
invalid distance too far back
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

we are happy with pako 1.0 right now but thought I'd let you know for 2.0

small reproducible issue with file simple.vcf.gz in repo here https://github.com/cmdcolin/pako_error

original source of file is https://dcc.icgc.org/api/v1/download?fn=/release_28/Projects/ALL-US/simple_somatic_mutation.open.ALL-US.tsv.gz (https://dcc.icgc.org/releases/release_28/Projects/ALL-US)

**Comment by puzrin** [comment]
Can this be dupe of #139? How that gzip was created? Multistream files have random fails (v1 also had those, but different).

See https://github.com/nodeca/pako/blob/master/test/gzip_specials.js#L74, the fail flows when chunkSize varies.

**Comment by cmdcolin** [comment]
it could be similar, I don't believe the file is bgzip though

$ file simple.vcf.gz                                                                                                                                                  
simple.vcf.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 11195
$ gunzip simple.vcf.gz                                                                                                                                                
$ gzip simple.vcf                                                                                                                                               
$ file simple.vcf.gz                                                                                                                                              
simple.vcf.gz: gzip compressed data, was "simple.vcf", last modified: Wed Mar  9 17:38:26 2022, from Unix, original size modulo 2^32 4733211      
$ file actualbgzipfile.gz
actualbgzipfile.gz: Blocked GNU Zip Format (BGZF; gzip compatible), block length 2380                                                                                                                  
```

after re-gzipping works fine with 2.0

**Comment by cmdcolin** [comment]
and to be clear i don't actually have the provenance of the original file, just something I ran across

**Comment by puzrin** [comment]
I'd suggest close as dupe of known problem, and attach sample to #139 for sure.

AFAIK, multistream (with sync flush in the middle) is the only case, causing random inflate fuckups.

**Comment by cmdcolin** [comment]
sounds good :) will do
