### ISSUE TITLE
discrepency between zlib and pako functions

### ISSUE THREAD

**Issue by crimson-med** [nodeca/pako#254]
Hello I have in my back end a simple system for encrypting and compressing data.

Backend NodeJS
```ts
export const aesEncrypt = (text: string, key: string = ENCRYPTION_KEY) => {
    let iv = randomBytes(IV_LENGTH);
    let cipher = createCipheriv('aes-256-cbc', Buffer.from(key), iv);
    let encrypted = cipher.update(text);
    encrypted = Buffer.concat([encrypted, cipher.final()]);
    return iv.toString('hex') + ':' + encrypted.toString('hex');
}

export const textCompressToBase64Url = (text: string) => {
    return deflateSync(text).toString('base64url')
}

export const packDataForUrl = (data: string, key: string = ENCRYPTION_KEY) => {
    return textCompressToBase64Url(aesEncrypt(data, key))
}

```

Result string:

```
eJwVU8cRxDAIbIkowXUjUv8lHP55BoM2Bp_W59hmGWH0DrxKpMlumMlfgAKD2DBKEx0gJs9j2ll-D7Gfl2PAgn1dPN696eDor3dWdR4iHH3hGQRKqKVy790Dneo7VZMEelNVag-n4rKAjhn4NNCiMmqwQ7QHMjgfkk0Rd3GlyviJuxz2zJWh6-_oAd4z9WHQPMhXgQ7P3LkegZHMt9-8h_IA-qSfm5LVIxn3PMJ0DEZSefcNW4CVKMluHkfhqjdIyXSPPWdeJGeJUWjInVq4E3tCClEQq2NSDFfA1QjSi71twSRRoMMk7GtceDIzTCHm9iqjFcB3D0U-N6tTIdnnkpnf_VpHDBJ5VnVZas7DQMVUrUu5TWXZV81j378DjVsYsGhdI7j7my6mFT6HH5dxxusT6_CiKpISF-u3A8U4O-aguJbnMapTBa0R8qEf6iK_GsZoZ89ZuTkBNoCazYWwUR8nQ0jBq9xu6Vr70nMKwAHeXWSNhI4qOS6QjSvtDg_iLoQVRmfAy_RVv3yN7buUFS6MiKCf0yVsgqr8KqYYXf0zR56utsdzXLFGauMhJ7QggHSphe0bwH1DyuQJT-DGAyfgUltmP4JcPUJ0akPPB0NTW6bV-61OIGcSV7N1zcik1_67QIH1c6i3An5X41WgZZfugnkWRxYF-2LxMuskueL8dNV_z7Ub5StKPVmZ2e52Y5M3I905SlaVdG2rF9X5dFg307uxiak2vgYSruvggU07bhP5wV273c6-Z65Zd_mjb0HXXs7pe-mrA-lsHzQZNvp8z2jt4rrID89spGGlyLdsagOyWd-eX13TX1DmNhnRdkMzt0NRHivqORe3nH_9zDtg
```

I then try to use `Pako` in the frontend to deflate before doing a AES decrypt however i keep getting various errors:
Below is how I convert the base64url to base64 (this works fine)

```
export const textDecompressFromBase64Url = (text: string) => {
    //@ts-ignore
    const sanitizedbase64 = text.replace(/_/g, '/').replace(/-/g, '+')
    const compressData = sanitizedbase64.split('').map((e) => {
        return e.charCodeAt(0);
    });
    const binData = new Uint8Array(compressData);
    const inflated = inflate(binData, { raw: true }).toString()
    return inflated
}
```

If I don't use `{ raw: true }` I get the following error in the inflate method: 

```
incorrect header check
```

If I pass the `{raw: true}` I get the following: 

```
invalid code lengths set
```

In the backend however i'm able to inflate with zlib with no issue:

```
export const textDecompressFromBase64Url = (text: string) => {
    return inflateSync(Buffer.from(text, 'base64')).toString()
}
```

**Comment by puzrin** [comment]
Please, remove everything, not related to pako, and leave only minimal code, with deflate/inflate call. If problem still exists - let me know.

**Comment by crimson-med** [comment]
i'm pretty sure closing the issue is not gonna solve the fact that the inflate pako function doesn't work like the zlib one.

**Comment by puzrin** [comment]
Sorry, but here are no room to debug your code for free. This package is stable, and has tests about topic. If you pretend to claim about bugs, you are expected to provide appropriate proofs, not just statements.

**Comment by crimson-med** [comment]
I gave the example the result of the same function `pako inflate` and `zlib inflate` is completely different. same input and different output so i'm pretty sure that would be considered a bug.
 I don't know what more proof you need to acknowledge the bug. 
 
 It's definitely not stable if there are 5 issues open by the way.

**Comment by puzrin** [comment]
Your example had a lot of extra code, and second one had unknown data source. That's not serious. This repo has reproducible tests, where textures generation can be verified. If you have different results - it's logical to investigate deviations in your code, instead of ask devs to spend their time.

> It's definitely not stable if there are 5 issues open by the way.

Please note, if you have default permissions to post in this tracker, that does not mean you are welcome with anything.

**Comment by crimson-med** [comment]
the data comes from simple deflate. I posted in the bigger code but you were too lazy to read it.

Its very simple:

zlib.deflate(mystring) = stringA
zlib.inflate(stringA) = originalData

pako.inflate(stringA) = random data

I gave the full example with zlib in the post but you deemed it useless. Then you ask me proof it doesn't work but you ignore the proof so i'm a bit lost at what you need.

**Comment by crimson-med** [comment]
To add onto this the inflate from the package `fflate` works fine so I wonder why pako one doesn't work if it's a `perfect reproduction of `zlib`

https://www.npmjs.com/package/fflate

**Comment by puzrin** [comment]
Your examples requires to much extra time to investigate. 

- Minimal example is something like calling pako deflate + pako inflate + zlib inflate.
- Minimal example is just a sortest possible code to execute.

When example is simple + easy to reproduce => answer will be easy. When your example has explanations instead of simple executable code, and requires extra time => that's usually rejected.

**Comment by crimson-med** [comment]
Bro you be funny that is exactly what I gave.

```
// Imports
import {infalte} from "pako"
import {inflateSync} from "zlib"
//Data 
const testString = `eJwVU8cRxDAIbIkowXUjUv8lHP55BoM2Bp_W59hmGWH0DrxKpMlumMlfgAKD2DBKEx0gJs9j2ll-D7Gfl2PAgn1dPN696eDor3dWdR4iHH3hGQRKqKVy790Dneo7VZMEelNVag-n4rKAjhn4NNCiMmqwQ7QHMjgfkk0Rd3GlyviJuxz2zJWh6-_oAd4z9WHQPMhXgQ7P3LkegZHMt9-8h_IA-qSfm5LVIxn3PMJ0DEZSefcNW4CVKMluHkfhqjdIyXSPPWdeJGeJUWjInVq4E3tCClEQq2NSDFfA1QjSi71twSRRoMMk7GtceDIzTCHm9iqjFcB3D0U-N6tTIdnnkpnf_VpHDBJ5VnVZas7DQMVUrUu5TWXZV81j378DjVsYsGhdI7j7my6mFT6HH5dxxusT6_CiKpISF-u3A8U4O-aguJbnMapTBa0R8qEf6iK_GsZoZ89ZuTkBNoCazYWwUR8nQ0jBq9xu6Vr70nMKwAHeXWSNhI4qOS6QjSvtDg_iLoQVRmfAy_RVv3yN7buUFS6MiKCf0yVsgqr8KqYYXf0zR56utsdzXLFGauMhJ7QggHSphe0bwH1DyuQJT-DGAyfgUltmP4JcPUJ0akPPB0NTW6bV-61OIGcSV7N1zcik1_67QIH1c6i3An5X41WgZZfugnkWRxYF-2LxMuskueL8dNV_z7Ub5StKPVmZ2e52Y5M3I905SlaVdG2rF9X5dFg307uxiak2vgYSruvggU07bhP5wV273c6-Z65Zd_mjb0HXXs7pe-mrA-lsHzQZNvp8z2jt4rrID89spGGlyLdsagOyWd-eX13TX1DmNhnRdkMzt0NRHivqORe3nH_9zDtg`


//@ts-ignore
const sanitizedbase64 = text.replace(/_/g, '/').replace(/-/g, '+')
const testData = convertDataURIToBinary(sanitizedbase64)
console.log(inflate(testData).toString())
console.log(inflateSync(Buffer.from(text, 'base64')).toString())
```

The two console.log are completly different and not the same data

**Comment by puzrin** [comment]
- `testString` - "magical" constant (no info how data was generated)
- `convertDataURIToBinary` + `text.replace` - suspicious operations, probably not needed for example at all.

See my answer https://github.com/nodeca/pako/issues/254#issuecomment-1153115136. I described sample sequence (pako deflate + pako inflate + zlib inflate) how to minimize code and possible human mistakes. Also, it would be nice if you play with existing tests before ask anything.

**Comment by crimson-med** [comment]
I explained how the string was generated in the previous example which you were too lazy to read. 

the string is a simple base64 string from data. 

The point is simple if I use `inflateSync(Buffer.from(text, 'base64')).toString()` from zlib I get the uncompressed data.

pako.inflate does not take a string as input only buffer so I can't do: `pako inflate(testData)` the function `convertDataURIToBinary` simply transforms a string into a `Uint8Array`

pako.inflate does simply not return the data the same as zlib.inflate does in this example. If you want I can make a public repo that showcases the example of how pako.inflate doesn't work in this case

**Comment by puzrin** [comment]
See https://github.com/nodeca/pako/blob/master/support/build_fixtures.js#L8-L10 (node should be < v12.17.0). This repo really has appropriate tests. You can just add your fixture, and if problem exists - this will be easy proof of no code mistake.

**Comment by 101arrowz** [comment]
FWIW I tested this and it works fine equally with `fflate.unzlibSync(data)` and `pako.inflate(data)`.

```js
const src = `eJwVU8cRxDAIbIkowXUjUv8lHP55BoM2Bp_W59hmGWH0DrxKpMlumMlfgAKD2DBKEx0gJs9j2ll-D7Gfl2PAgn1dPN696eDor3dWdR4iHH3hGQRKqKVy790Dneo7VZMEelNVag-n4rKAjhn4NNCiMmqwQ7QHMjgfkk0Rd3GlyviJuxz2zJWh6-_oAd4z9WHQPMhXgQ7P3LkegZHMt9-8h_IA-qSfm5LVIxn3PMJ0DEZSefcNW4CVKMluHkfhqjdIyXSPPWdeJGeJUWjInVq4E3tCClEQq2NSDFfA1QjSi71twSRRoMMk7GtceDIzTCHm9iqjFcB3D0U-N6tTIdnnkpnf_VpHDBJ5VnVZas7DQMVUrUu5TWXZV81j378DjVsYsGhdI7j7my6mFT6HH5dxxusT6_CiKpISF-u3A8U4O-aguJbnMapTBa0R8qEf6iK_GsZoZ89ZuTkBNoCazYWwUR8nQ0jBq9xu6Vr70nMKwAHeXWSNhI4qOS6QjSvtDg_iLoQVRmfAy_RVv3yN7buUFS6MiKCf0yVsgqr8KqYYXf0zR56utsdzXLFGauMhJ7QggHSphe0bwH1DyuQJT-DGAyfgUltmP4JcPUJ0akPPB0NTW6bV-61OIGcSV7N1zcik1_67QIH1c6i3An5X41WgZZfugnkWRxYF-2LxMuskueL8dNV_z7Ub5StKPVmZ2e52Y5M3I905SlaVdG2rF9X5dFg307uxiak2vgYSruvggU07bhP5wV273c6-Z65Zd_mjb0HXXs7pe-mrA-lsHzQZNvp8z2jt4rrID89spGGlyLdsagOyWd-eX13TX1DmNhnRdkMzt0NRHivqORe3nH_9zDtg`

const decodedbstr = atob(src.replace(/_/g, '/').replace(/-/g, '+'));
const decoded = new Uint8Array(decodedbstr.split('').map(c => c.charCodeAt(0)));

// pako.inflate(decoded) and fflate.unzlibSync(decoded) both work
```

**Comment by dae550** [comment]
bug has not been fixed. pako does not implement zlib correctly
