### ISSUE TITLE
[observation & proposal]: potential usage of memory pools for less memory allocations

### ISSUE THREAD

**Issue by tmarti** [nodeca/pako#258]
Hello!

Been playing a bit with this awesome library `pako.js` in the context of decompressing multiple compressed streams from a Web application, and found something really interesting.

Your library uses the concept of `chunkSize` in order to generate small memory buffers (`Uint8Array`) as the data gets decompressed, and the whole stream decompression finishes, it joins together those small chunks (think by default the chunk size is 16 KB) to generate the final decompressed `byte-array`.

I think this is pretty optimal if you just want to decompress one compressed stream of say 16 MB inflated size:

- it will generate 2^10 chunks of 16 KB and join them together at the end.
  So it will invoke `new Uint8Array` with a total size of 32 MB: 16 MB for the individual chunks plus 16 MB for the final inflated `byte-array`

But in the case you need to decompress for example 100 streams of same 16 MB inflated size streams, following will happen:
- it will do same same as previous invocation but x100 times: 100 * 16 MB for the individual chinks plus 100 * 16 MB for the final inflated `byte-array`.

The problem here is not memory consumption:
- in the single stream case, at the end the browser (after garbage collecting the small 16 KB temporary chunks) will use 16 MB of RAM, which is perfect given that's your inflated data size
- in the 100 streams case, at the end the browser (again, after the garbabe collection of the small 16 KB temporary chunks) will use 100 * 16 = 1600 MB of RAM, which is ALSO perfect given again that's your inflated data size

So, if that was not the problem, what is the problem then? Well, it's the stress on the garbage collector and the amount of small-size memory allocations

- for the single stream case, it will need to do `16 MB / 16 KB = 1k` allocations of 16 KB-`Uin8tArrays`
- for the 100 streams case, it will need to do `1600 MB / 16 KB = 100k` allocations of 16 KB-`Uint8Arrays`, and the Js engine will need to garbage collect 100k objects.

This amount of stress to the Garbage Collector, I've observed it's a REALLY bad idea both on NodeJS and the Browser (especially when working on data-instensive applications). In theory garbage collectors "just work well" but in practice "you have to be nice to them".

Especially on the mobile, in the 100 streams case, even when your mobile browser might have 4GB of RAM available, garbage collecting 100k small chunks of 16 KB will most probably crash the browser in your device.

Don't have the time now to continue ellaborating this but will ellaborate about it soon 😃, there is a potentially really good option by using temporary memory pools (oh, like in the old only-C/C++ days 😄) in which the 100 streams case gets the number of temporary chunk memory allocations reduced from 100k allocations to 1k allocations, even though that would require introducing some "sugar code" to `pako.js` to support that as an initialization option and you might want to get further feedback / conversation about that possibility.

> And yes, with this technique applied the 1600 MB of inflated data just load well in mobile browsers and in a really stable way 🤗

**Comment by puzrin** [comment]
Current wrapper is trade-off between simplicity and use cases coverage. You can create your own for specific edge case. It's technically impossible to create single wrapper for all possible demands.
