### ISSUE TITLE
Getting corrupted data on decompressing

### ISSUE THREAD

**Issue by mnithishkumar** [nodeca/pako#287]
Hi team,
Currently I have used the pako to compress a JSON object and store the compressed data in a redis data. 

The compressed data is stored as a Buffer format. Once stored in Redis and retrieved the same data is getting back as Corrupted data.
Corrupted Data:
`z0�&c:♠▬GBO��˒񵚌@�w�▼‼��?[��C�0�e�qws�e��n���
�>d��Lɡ�d)W8���$���∟оojǁV��♥▼▬��ؔq⌂��Ք�V�3ۇ]�F����EZ►B���c|
��→�y◄�U�e�☻�♣♀▬�↑�☺���*T��-#��..X���.��r6Nʈ�a`§��
�~��I��R�↓�̎�ڎIY�:▲�xC҂��][X�i�R�{��"   �@§v\�x♀�♫;� /t�¶U�
U���ϻ|♀nA��F�̓&m�-1.I��iG���EX[�ߦI�→,�4w�+���Jqe&����Mr♠`l§`  

So, the application is not able to decompress this kind of data and returns with a 504-server error. This error seems to be intermittent.

**Comment by puzrin** [comment]
Sorry, can't help with your application debugging. If you wish report bug in this package - please provide a reproducible sample without external dependencies.
