### ISSUE TITLE
Z_SYNC_FLUSH not working

### ISSUE THREAD

**Issue by creationix** [nodeca/pako#34]
I have a use case where I want to make a TCP binary protocol for internal use.  The protocol has a lot of repeated values eating up bandwidth.  It would be great if I could apply a generic deflate/inflate over the stream.

I will be sending many smallish messages (< 1k) and I need the data to flush right away.  But it is a stream and I want to reuse symbols from earlier in the stream.  Looking at the options, `Z_SYNC_FLUSH` appears to be exactly what I need, but it's not working.  I can't get `Deflate` to `onData` anything unless I send a `Z_FINISH`.  But then the stream is dead and I can't send later messages.

``` js
var Deflate = require('pako').Deflate;
var Z_SYNC_FLUSH = require('pako').Z_SYNC_FLUSH;

var d = new Deflate();
d.onData = function (chunk) {
  console.log("onData", chunk);
};
d.push("some data", Z_SYNC_FLUSH);
d.push("some more data", Z_SYNC_FLUSH);
```

If you run this code in node, the `onData` handler is never fired.  It only outputs data if I send a `Z_FINISH` message.

**Comment by puzrin** [comment]
@creationix i don't know if you still interested, but i think patch needed for this deflate wrapper line https://github.com/nodeca/pako/blob/master/lib/deflate.js#L227

```js
    if (strm.avail_out === 0 || (strm.avail_in === 0 && _mode !== Z_NO_FLUSH)) {
```

...and the same for inflate wrapper.

I did't tested it, because don't have appropriate tasks to check in real life.
