### ISSUE TITLE
Pako fails inflate on concatenated gzip files

### ISSUE THREAD

**Issue by ttrevorr** [nodeca/pako#35]
Use inflate.push to add data to pako inflate stream on gzip files created by concatenating them.  Pako fails when you try and push more data past the first gz file.  This is a single gzip file created by concatenating multiple gzip files together.  The files inflate fine in zlib, etc. Inflating the file outside of Pako and then re-deflate allows the file to be inflated correctly by Pako.

To reproduce: 
1. Create two different gzip files and then concatenate them together.
2. Try to inflate in Pako using inflate.push with file slices smaller than the total files size.
3. When you try to push another slice onto the inflate stream PAST the first concatenated gz file the push method returns false with no error code.

JSFiddle of example code that fails on concatenated gzip files: 
http://jsfiddle.net/jlovell19/d3km6db6/5/

Per the RFC:
"A gzip file consists of a series of "members" (compressed data sets). [...] The members simply appear one after another in the file, with no additional information before, between, or after them."

Advanced usage of gzip explaining concatenated gzip files:
http://www.gnu.org/software/gzip/manual/gzip.html#Advanced-usage

I can provide a sample file if needed.

**Comment by danvk** [comment]
In case anyone else needs to do this, I'm using this snippet to inflate concatenated gzip files using pako:

```javascript
function inflateConcatenatedGzip(buffer) {
  var position = 0;
  var blocks = [];
  do {
    var inflator = new pako.Inflate();
    inflator.push(buffer.slice(position));
    if (inflator.err) { throw inflator.msg; }
    blocks.push(inflator.result);
    position += inflator.strm.total_in;
  } while (inflator.strm.avail_in > 0);
  return blocks;
}
```

**Comment by ThatBean** [comment]
modified code from @danvk, to inflate concatenated gzip arrayBuffer in modern browser.

```js
{
  const loadPako = () => window.pako || fetch(`https://unpkg.com/pako@1.0.6/dist/pako.min.js`)
    .then((response) => response.text())
    .then((text) => eval(text))
    .then(() => window.pako)

  const concatArrayBuffer = (arrayBufferList = []) => {
    const resultTypedArray = new Uint8Array(arrayBufferList.reduce((o, arrayBuffer) => o + arrayBuffer.byteLength, 0))
    let byteOffset = 0
    arrayBufferList.forEach((arrayBuffer) => {
      const { byteLength } = arrayBuffer
      resultTypedArray.set(new Uint8Array(arrayBuffer), byteOffset)
      byteOffset += byteLength
    })
    return resultTypedArray.buffer
  }

  const gunzipAll = (PAKO, arrayBuffer) => {
    const arrayBufferList = []
    let byteOffset = 0
    let byteLeft = 1
    while (byteLeft > 0) {
      const inflator = new PAKO.Inflate()
      inflator.push(new Uint8Array(arrayBuffer, byteOffset))
      if (inflator.err) throw inflator.msg
      arrayBufferList.push(inflator.result)
      byteOffset += inflator.strm.total_in
      byteLeft = inflator.strm.avail_in
    }
    return concatArrayBuffer(arrayBufferList)
  }
}
```

**Comment by sakoht** [comment]
Seems like a regular thing for the interface to this library needing a wrapper of some sort, and everyone needing the same wrappers.  

Does that project exist somewhere?

I can't seem to find it.  But I have a lot of code that is derived from things people posted in github issues.  And am learning more about zlib internals than would be ideal.

Right now looking for something that has done this with a gz file so big the content needs to be streamed.  I can't find that _yet_.

**Comment by wholenews** [comment]
The above code worked for me in browser but not Node.JS.  It seems that `strm.avail_in` never decreases in Node.  With the added sanity check that `position < buffer.byteLength` the code completes with corrupted results.  A comparison of browser and Node.JS execution shows different successive `position` values for the same file.

**Comment by dr-js** [comment]
@wholenews if you're using code from https://github.com/nodeca/pako/issues/35#issuecomment-437341187, then my guess is you used Node.js `Buffer.buffer` directly as `ArrayBuffer`, the problem would be some Node.js Buffer is internally shared, and need code like [toArrayBuffer](https://github.com/dr-js/dr-js/blob/24aacc68/source/node/data/Buffer.js#L6-L13) to convert them correctly.
