### ISSUE TITLE
Revisit supported modes for inflate/deflate wrappers

### ISSUE THREAD

**Issue by puzrin** [nodeca/pako#37]
Inspired by #34. Current docs for external API is not precise and can confuse users, that pako high-level interface really support all modes, that can be used via zlib directly. That's not true.

We should review docs, and decide, how to fix and provide correct recommendations, when it's better to use low-level zlib API `./lib/zlib` directly with custom wrapper:

1. Add missed modes, if that's simple and will not make wrapper code completely mad.
2. Fix docs to say clear which modes are supported and not supported.

**Comment by TimurAditazz** [comment]
pako is the brilliant!
