### ISSUE TITLE
Download failed of the latest release.

### ISSUE THREAD

**Issue by mgaert** [nodeca/pako#47]
Hi,
I faced the issue that I could not install Pako using npm.
First error I got was:
- error shasum check failed for C:\Users\mgaert\AppData\Local\Temp\npm-8108-77644fd9\registry.npmjs.org\pako\-\pako-0.2.5.tgz
- error Expected: 36df19467a3879152e9adcc44784f07d0a80c525
- error Actual:   c469fd3ea0829492caf628d208b6094e78063f05

Second error I could not download manually frum git.

Info:
Im I am using npm v2.1.18 and notejs v0.10.35

Regards
Michael

**Comment by puzrin** [comment]
That's npm or your provider issue, not pako one.
