### ISSUE TITLE
Benchmark node v0.12 and io.js

### ISSUE THREAD

**Issue by alippai** [nodeca/pako#50]
The current IO.js has nice pako performance (>20% increase)

**Comment by alippai** [comment]
Should I add a pull request to the README.md, this is a "won't fix" or will you do this later?

**Comment by puzrin** [comment]
Ah, didn't understood scope of this ticket. Sorry.

Well, what is reason to add more benchmarks? Those will make page longer, and more difficult to reach examples, IMHO.

**Comment by alippai** [comment]
Node 0.10 and 0.11 are not the latest stable or development versions
anymore. We shouldn't expose benchmarks for legacy/maintenance versions.
Also your numbers are better on the fresh versions.

**Comment by puzrin** [comment]
0.12 and iojs have problems with stream, and produce result not relevant to real zlib performance.

Those dumps are to show principle, that JS can be very fast. There are no goal to benchmark every node version. Adding more benchmarks will not help users anyhow with package use, IMHO.
