### ISSUE TITLE
Is this library compatible with the Java GZip implementation?

### ISSUE THREAD

**Issue by wwwpol** [nodeca/pako#51]
Our backend is using the Java GZipInputStream to decode the gzip JSON from the web layer.  Do you know if it is compatible?

http://docs.oracle.com/javase/7/docs/api/java/util/zip/GZIPInputStream.html

**Comment by puzrin** [comment]
No ideas. That's zlib port.

**Comment by gandhirajan** [comment]
Yes it is. Managed to test it.
