### ISSUE TITLE
gzip function makes browser unresponsive

### ISSUE THREAD

**Issue by wwwpol** [nodeca/pako#53]
I am calling the gzip function and passing plain old JSON.  When I do, the browser freezes.  I look in activity monitor and Chrome helper is taking up 100% cpu.

**Comment by puzrin** [comment]
I have low telepathy skills to understand what happens. If you are sure this is bug, code snippets needed to reproduce. But read docs & test sources first, where are enougth examples how to use this lib.

**Comment by apitts** [comment]
I too had this issue initially.  It's likely that you are passing an object rather than a valid data type if you wrap your object in JSON.stringify( ) then it should work.
