### ISSUE TITLE
Error decoding content

### ISSUE THREAD

**Issue by apitts** [nodeca/pako#55]
I am trying to upload some gzipped json content to s3 and keep running into an ERR_CONTENT_DECODING_FAILED error, which would suggest there is something awry with the encoding. Hopefully there is something straightforward that I've missed.  

Here is what I'm using on the client: 
```javascript
      $upload.http({
        method: 'PUT',
        headers: {'Content-Type': 'application/json', 'Content-Encoding': 'gzip'},
        url: response.s3URL,
        data: pako.gzip(JSON.stringify(networkForUpload), {to: 'string'})
      }).success(function(data) {
       //Do more stuff
      });
```

And the server to get the signed url:
```javascript
      s3.getSignedUrl('putObject', {
        Bucket: config.bucketNames.uploadedNetworks,
        Expires: 300,
        Key: network._id.toString(),
        ContentType: 'application/json',
        ContentEncoding: 'gzip',
        ACL: 'public-read'
      }, function(err, data) {
      //Do more stuff
      });

**Comment by puzrin** [comment]
`data: pako.gzip(JSON.stringify(networkForUpload), {to: 'string'})` i'm not sure this will be  converted in request to proper equivalent of gzipped body.

It's better to ask such question at SO, because it's not related anyhow to gzipping algorythm. But you can be sure, that pako's output is 100% equal to one from zlib.

**Comment by apitts** [comment]
Understood.  Thanks @puzrin! I will ask on SO...have tried everything I could think of to solve the issue today.

**Comment by puzrin** [comment]
You probably need to pass ArrayBuffer to xhr, and make sure server side can really decode gzipped data. But i never did it, and can not say exactly how to implement gzipped http request from client.

**Comment by apitts** [comment]
Thanks! I'll give that a go and keep plugging away at it.

**Comment by apitts** [comment]
Just in case anyone comes across this issue. A nice solution to this problem was to write a simple Lambda function that gzip's an object on an S3 PUT event.
