### ISSUE TITLE
Not recognized as a valid gzip in Java (java.util.zi.GZIPInputStream)

### ISSUE THREAD

**Issue by vedmack** [nodeca/pako#56]
Hi,

I tried to gzip with *pako* on client side and send it to my server (java) and to ungzip it there by using *GZIPInputStream* , but it yells that is not a valid gzip archive, can it be that data that gzipped with *pako* can't be ungzipped with other gzip implementation (for example Java GZIPInputStream) ?

**Comment by puzrin** [comment]
99.9% problem is in improper send and data reencoding, or imroper decoder use. Pako's output is binary equal to zlib. See tests, those are done with compare to zlib output.

I don't use java and can't advice anything about it.
