### ISSUE TITLE
RangeError: Size is too large (or is negative)

### ISSUE THREAD

**Issue by NekR** [nodeca/pako#58]
I am getting this on BB10 and in some cases on iOS Safari (when app is launched from Home Screen). Seems like there is some limit on buffers processing at a same time.

Any idea how to fix it?

**Comment by puzrin** [comment]
Need code example.

**Comment by puzrin** [comment]
Any news? If your env has limits to max typed array size, that's not pako issue. You probably need use wrapper to store data in blobs. There are no such error text in pako ("size is too large")

**Comment by NekR** [comment]
Hmm.. my env? I do not think iOS is mine. Also I never said that its pako issue. Code is simple ``inflateRaw(new Uint8Array(buffer))`` where buffer is deflated file of any size.

I already figured out why that was happening, but firstly just tried to reach other people here how may now it.

**Comment by puzrin** [comment]
You cant use ANY size of typed array. There are limits ~ 400mb even on desktops. You have to use blobs with chunking with large data. Chunking examples are available in api docs.

**Comment by NekR** [comment]
@puzrin by ANY size I meant that browser crashes with buffer of any given size, like 1kb, 10kb or 10mb.

**Comment by puzrin** [comment]
Can you provide exact error text and stack trace? I need example, showing that that error happens in pako sources with small binary size. No ideas why this can happen with small buffer sizes. Internally pako allocates only 32K window buffer.

**Comment by NekR** [comment]
That is actually a bug in iOS Home Screen apps, it's related to memory corruption, so buffer gets wrong size/data. Fortunately, it's fixed already in iOS 8.4.

There was just a little change to get error report because most of the time browser crashes. Later I figured out that affects not only buffers, but for example ``JSON`` API. Sorry for the frustration, at first I thought that it's a pako issues because first error which I get was ``RangeError: Size is too large (or is negative)`` thrown from ``inflateRaw``. Now it's clear that it's UA bug.

**Comment by puzrin** [comment]
No problem. So, everything is ok and we should not add warnings for developpers in readme?

**Comment by NekR** [comment]
Yes, everything is okay with pako and those problems is not related to it. I.e. it works on iOS perfectly and even on Home Screen apps, unless user will encounter that memory corruption bug, but that bug affects everything, so then almost anything can trigger a crash. Thanks for helping though!
