### ISSUE TITLE
What about encoding?

### ISSUE THREAD

**Issue by maksaimer** [nodeca/pako#63]
For example, from server i received string: H4sIAAAAAAAAAAEYAOf/ItCS0YHQtdC8INC/0YDQuNCy0LXRgiEieN0AthgAAAA= 

If I try decode in terminal:
echo 'H4sIAAAAAAAAAAEYAOf/ItCS0YHQtdC8INC/0YDQuNCy0LXRgiEieN0AthgAAAA=' | base64 -d | gunzip

Result: "Всем привет!"

If I try decode in browser by code:
var data = "H4sIAAAAAAAAAAEYAOf/ItCS0YHQtdC8INC/0YDQuNCy0LXRgiEieN0AthgAAAA=";
var strData     = atob(data);
var charData    = strData.split('').map(function(x){return x.charCodeAt(0);});
var binData     = new Uint8Array(charData);
console.log(String.fromCharCode.apply(null, new Uint8Array(pako.inflate(binData))));

Result: "ÐÑÐµÐ¼ Ð¿ÑÐ¸Ð²ÐµÑ!"

How i can resolve it?

**Comment by maksaimer** [comment]
I found similar issue in closed issues https://github.com/nodeca/pako/issues/32
But options { to: 'string' } don't fix my problem :(

**Comment by maksaimer** [comment]
Full version of test code
```javascript
// Get some base64 encoded binary data from the server.
        var b64Data     = 'H4sIAAAAAAAAAAEYAOf/ItCS0YHQtdC8INC/0YDQuNCy0LXRgiEieN0AthgAAAA=';

        // Decode base64 (convert ascii to binary)
        var strData     = atob(b64Data);

        // Convert binary string to character-number array
        var charData    = strData.split('').map(function(x){return x.charCodeAt(0);});

        var binData     = new Uint8Array(charData);
        var data        = pako.inflate(binData, { to: 'string' });
        var strData     = String.fromCharCode.apply(null, new Uint16Array(data));

        console.log(strData);

        var test = { my: 'Всем привет!' };

        var binaryString = pako.deflate(JSON.stringify(test), { to: 'string' });
        var restored = JSON.parse(pako.inflate(binaryString, { to: 'string' }));

        console.log('restored.my: ' + restored.my);
```

**Comment by puzrin** [comment]
```js
pako = require('pako');
atob = require('atob');

var b64Data     = 'H4sIAAAAAAAAAAEYAOf/ItCS0YHQtdC8INC/0YDQuNCy0LXRgiEieN0AthgAAAA=';

// Decode base64 (convert ascii to binary)
var strData     = atob(b64Data);

var data        = pako.inflate(strData, { to: 'string' });

console.log(data);

var test = { my: 'Всем привет!' };

var binaryString = pako.deflate(JSON.stringify(test), { to: 'string' });
var restored = JSON.parse(pako.inflate(binaryString, { to: 'string' }));

console.log('restored.my: ' + restored.my);
```

1. No need to cheat with strings if you use 'toString'
2. You have correct result but probably wrong html page encoding

**Comment by maksaimer** [comment]
Thank you, you resolve issue
