### ISSUE TITLE
How to decompress this string?

### ISSUE THREAD

**Issue by ajenkul** [nodeca/pako#64]
I have this string `X'737AB86B719E82CBC3DDDDC9190ABE0F77CFCE54303230300200'` as a raw deflate data. But I don't know how to use pako to decompress this into original string before compress. Please help me!

**Comment by alexeyten** [comment]
http://nodeca.github.io/pako/#inflateRaw
```js
var s = Buffer('737AB86B719E82CBC3DDDDC9190ABE0F77CFCE54303230300200', 'hex').toString('binary');
var result = pako.inflateRaw(s, {to: 'string'});
// result = 'Bản Dịch Mới 2002'
```

**Comment by ajenkul** [comment]
Wow, that very kind of you. Thanks you so so much.

**Comment by ajenkul** [comment]
@alexeyten I'm using Javascript at client-side (not use Node.JS). So, could you please hint me any class to replace with Buffer class?
