### ISSUE TITLE
`inflateReset` not resetting some internal state

### ISSUE THREAD

**Issue by jvilk** [nodeca/pako#68]
First off: Thanks for this library. I'm using your zlib implementation directly to implement the JDK's [zip file support](https://github.com/plasma-umass/doppio/blob/jar_jdk/src/natives/java_util.ts#L341) in my JavaScript JVM. :)

I found that there's an issue with `inflateReset` that prevents subsequent reuse of the ZStream from working properly. You're following the exact same logic from zlib's implementation, and I couldn't find the bug... but I think it may have to do with the extra JavaScript state you track inside the ZStream. I wasn't able to find the problem. As a workaround, [I create new ZStreams instead](https://github.com/plasma-umass/doppio/blob/jar_jdk/src/natives/java_util.ts#L468), but I wanted to alert you to the problem.

The problem manifests [at this line](https://github.com/nodeca/pako/blob/master/lib/zlib/inflate.js#L1290) when I try to re-use the ZStream.

I'd normally try to present you with a minimal test case that triggers the bug, but I don't have time. I decided to report the issue hoping that you'll immediately spot the issue -- and thinking that it's better to report the issue with no code than to not report it at all. :)

**Comment by puzrin** [comment]
I guess you do something wrong with api. Try `inflateReset2()` & `inflateInit2()`.

Anyway, since internals are 100% identic to zlib, such api questions should be forwarded to original lib.

**Comment by jvilk** [comment]
I also identically followed OpenJDK's implementation of the native methods 100%, but maybe you're right.

**Comment by jvilk** [comment]
[If you're curious, here's the original source file.](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/c98bd523e5f9/src/share/native/java/util/zip/Inflater.c#l193)
