### ISSUE TITLE
Deflate only distro

### ISSUE THREAD

**Issue by AdamMichaelLong** [nodeca/pako#70]
Hi, thanks for this great project! I am wondering is there a way to include just deflate distro of pako (pako.deflate) - in order to reduce the size of the library and how much would this actually reduce the size of pako?

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/tree/master/dist there are separate bower builds. And you can require only deflate if you use browserify.

**Comment by AdamMichaelLong** [comment]
super! :-)
