### ISSUE TITLE
How to compress a blob stream using pipes?

### ISSUE THREAD

**Issue by DanKlaud** [nodeca/pako#72]
Hi everyone!,
I'm trying to deflate a blob stream from socket-io-stream output at client-side. 
Is it possible to pipe pako.deflate ( or some option) in order to compress stream data?

This is my code : 
 // this function gets the blobFile from the event
function FileChosen(evnt) {   blobFile = evnt.target.files[0]; } 

//  'ss' is the  socket.io-stream object
stream = ss.createStream();                                                    
// 'socket' comes from  io.connect('http...');  from socket.io
ss(socket).emit('transfer', stream, {'id'  : data.id });                  
                                                                                                
// this create the blob stream using socket.io-stream
blobStream = ss.createBlobReadStream( blobFile, { highWaterMark: 3145728, start: 90,  end: 99});

 // Can I pipe pako.deflate in this way??
blobStream.pipe(pako.deflate).pipe(stream);                         

// blobStream.pipe(stream);    // This way works but without compression

Thanks in advance.

**Comment by puzrin** [comment]
`pako` has no node-stream interface, and will not have. You need to write a wrapper. With `through2` for example.

**Comment by DanKlaud** [comment]
thank you so much.
