### ISSUE TITLE
Latest revision doesn't seem to work in a simple application

### ISSUE THREAD

**Issue by dozil** [nodeca/pako#75]
Downloaded latest revision of pako (1.0.0), and latest require.js (2.1.22), both using npm install.
Tried to integrate it in a small webpage project, using the provided example:
var pako = require('pako');
var input = new Uint8Array();
//... fill input data here
var output = pako.deflate(input);

Fails with the message:
mypage.html:87 Uncaught TypeError: pako.deflate is not a function

It seems that pako variable holds the following value:
localRequire(deps, callback, errback) {
                    var id, map, requireMod;

                    if (options.enableBuildCallback && callback && isFunction(callback)) {
              …

**Comment by puzrin** [comment]
That example is for node.js & for client sources, assembled with browserify/webpack and so on.

You probably need to use browser builds from `dist/` forlder. I don't use require.js, and have no ideas about it.
