### ISSUE TITLE
Unable to decompress using java

### ISSUE THREAD

**Issue by thepowerjeet** [nodeca/pako#76]
I compressed data in client side using pako (var compressedData = pako.deflate(str); )
and tried to decompress in server side using java but i am not getting it.
Why ,I don't know. I tried Inflator() java utility. can i get some help here ?

**Comment by puzrin** [comment]
Sorry, nobody can consult you here about java & generic programming questions. You can find some examples in `test` folder.

**Comment by thepowerjeet** [comment]
I mean ,just want to ask that It is possible to decompress pako compressed array in java.
Okay i will try test folder. Thanks

**Comment by puzrin** [comment]
Content is defined by some RFC and is binary equal to zlib's result. If you have standard inflate in java, you should be able to decompress.

**Comment by thepowerjeet** [comment]
okay thanks for your information.

**Comment by thepowerjeet** [comment]
okay thanks puzrin.
