### ISSUE TITLE
error -3: incorrect header check

### ISSUE THREAD

**Issue by r03ert0** [nodeca/pako#80]
Hello,

I have a text file compressed like this (either on OSX or Linux):
`zip file.txt.zip file.txt`

I try to decompress that file client-side using:
```
var xhr = new XMLHttpRequest();
xhr.open('GET', "data/file.txt.zip", true);
xhr.responseType = 'arraybuffer';
xhr.onload = function(e) {if (this.status == 200) {
    var data=pako.inflate(new Uint8Array(this.response));
}}
```

And I get the following error in the console:
`Uncaught incorrect header check`

Thank you for your help!

**Comment by puzrin** [comment]
This package is for deflate/inflate, not for zip. Try [jszip](https://github.com/Stuk/jszip) instead.

**Comment by r03ert0** [comment]
Thank you!

I don't mind using a different compression algorithm, so I did
`gzip file.txt`

and then
```
var xhr = new XMLHttpRequest();
xhr.open('GET', "data/file.txt.gz", true);
xhr.responseType = 'arraybuffer';
xhr.onload = function(e) {if (this.status == 200) {
	var data=pako.inflate(new Uint8Array(this.response),{to:'string'});
}}
```

and everything works now 👍 :D

**Comment by Aprodebug** [comment]
执行ungzip的时候有个错误，能帮忙看下是什么问题吗
Uncaught incorrect header check

---
`          var ajax = new XMLHttpRequest(); 
          ajax.open("get", url, true); 
          ajax.responseType = "arraybuffer"; 
          ajax.onload = function() {
            if (ajax.response) {
              var byteArray = new Uint8Array(ajax.response);
              byteArray = pako.ungzip(byteArray);
            } else {
              
            }
          };`
