### ISSUE TITLE
DOCS: what type of string encoding does 'deflate' use.

### ISSUE THREAD

**Issue by keyscores** [nodeca/pako#84]
Seems like browsers will encode in ASCII by default, and server/node will encode in UTF-8 ? Can you be more specific about how it is encoded?
Seems like I get an error when deflating in browser, and subsequently inflating in server.

**Comment by gandhirajan** [comment]
Are you getting error like not in valid gzip format in server side?

**Comment by puzrin** [comment]
@keyscores If you need to use strings instead of Uint8Arrray, those should be "binary" - 1 byte (char) per position. That's the same as array, but in string form.

That's not the same as JS strings (utf16)

**Comment by keyscores** [comment]
@puzrin what's the correct encoding to use with node Buffer in that case? 
Just to be clear here is what I'm trying to do:

```
// DEFLATE in browser...
var pako = require('pako')

var obj = [{ a: 1 }]
var string = JSON.stringify( obj )
var binaryString = pako.deflate( string, { to: 'string' });
var base64 = btoa(binaryString)
/// send to service on server ///

// INFLATE on server...
var buf = new Buffer(base64, 'base64');
var base64 = buf.toString('ascii')
console.log('to string utf ', base64 );

var json = JSON.parse(pako.inflate( base64 , { to: 'string' }));
// > Uncaught error in header

```

**Comment by puzrin** [comment]
@keyscores pako works with binary data on input and output (arrays or binary strings). Always. How do you get such data - it's on your choice (and your responsibility).

In your code first error is that JSON.stringify() returns NOT binary string but JS utf16 string.

**Comment by puzrin** [comment]
In inflate error is that you try to decompress base64 string instead of binary (buffer).

**Comment by keyscores** [comment]
@puzrin thanks for the input. 
1. I'm taking the stringify example directly from the pako readme : https://github.com/nodeca/pako#example--api
2. The decompress is of an 'ascii' string that has already been de-base64 . Seems correct when I look at the logs.

**Comment by puzrin** [comment]
Example is not very good. It relies on fact, that content is ascii (text 'test'), and that's compatible as binary input. Because ascii has 7-bit chars and binary has 8-bit chars.

Inflate must have binary data on input (array), in your case 7-bit ascii means completely broken data.

**Comment by puzrin** [comment]
I've added examples https://github.com/nodeca/pako/tree/master/examples.

Don't know about old browsers.

**Comment by keyscores** [comment]
@puzrin Thanks for the updated example. I'm trying it now.
