### ISSUE TITLE
Using pako for data that isn't a string or int array

### ISSUE THREAD

**Issue by tavonkelly** [nodeca/pako#87]
I'm trying to deflate and then inflate an array of floats, but it just converts the floats to integers. Is there any way to prevent this? I'm deflating a Float32Array, but after inflating it turns to Uint8Array.

**Comment by puzrin** [comment]
You should care about proper data conversion fore deflate and after deflate. See docs http://nodeca.github.io/pako/#deflate.

You can take AttayBuffer from you Float32Array and then create Uint32Array from it. The same back after deflate. See MDN docs about typed arrays.

**Comment by tavonkelly** [comment]
Ahh, thank you. I didn't think about converting the data to a Uint8Array before deflating it.

The docs for deflate saying `deflateRaw(data[, options])Uint8Array | Array | String` made me think that an Array of any type would be accepted.

I've got it working now. Thanks for your help.
