### ISSUE TITLE
Content-Encoding for Javascript Blob to use browser's built-in decompression?

### ISSUE THREAD

**Issue by optimalisatie** [nodeca/pako#88]
Hi!

I am investigating an idea to make use of the browsers built in gzip decompression facility by using the [Blob API](https://developer.mozilla.org/en-US/docs/Web/API/Blob). It appears that the only obstacle is the ability to set Content-Encoding for the blob.

I hereby want to inform if anyone knows of a solution to use a javascript Blob to uncompress gzip data.

The code that I use to test via the browser console is the following. It will change the background of a page to green on success.

```javascript
/* create blob */
var createBlobUrl = function(fileData,mimeType) {
    var blob;

    // Create blob
    try {
        blob = new Blob([fileData], {type: mimeType});
    } catch (e) { // Backwards-compatibility
        window.BlobBuilder = window.BlobBuilder || window.WebKitBlobBuilder || window.MozBlobBuilder;
        blob = new BlobBuilder();
        blob.append(fileData);
        blob = blob.getBlob(mimeType);
    }
    return URL.createObjectURL(blob);
};

/* CSS: body, * { background:green; } */
var zip = window.atob('H4sIAAAAAAAA/0vKT6nUUdBSqFZISkzOTi/KL81LsUovSk3Ns1aoBQCLj6wTHQAAAA==');

function str2bytes (str) {
    var bytes = new Uint8Array(str.length);
    for (var i=0; i<str.length; i++) {
        bytes[i] = str.charCodeAt(i);
    }
    return bytes;
}
var bloburl = createBlobUrl(str2bytes(zip),'text/css');
var link = document.createElement('link');
link.setAttribute('rel','stylesheet');
link.setAttribute('type','text/css');
link.setAttribute('href',bloburl);
document.head.appendChild(link);

```

**Comment by puzrin** [comment]
Blob does not support decompression. It's just a cunked store for binary data, with some slicing methods. If you have huge files, you can use Blob to pipe data in/out pako, for reducing peak memory use.

**Comment by optimalisatie** [comment]
Hi Puzrin,

Thank you for the fast response and insights! I hope that you appreciate the potential suggestion in regards of new javascript gzip decompression options.

Regarding the Blob, I understand that the Blob itself will not support decompressing but with a trick the browser may do the work when the Blob is referenced as an Object URL via `URL.createObjectURL` and then inserted in the DOM. 

https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

If it would be possible to set the content-encoding of the Blob Object to gzip the browser will decompress the Blob and with a trick it will be possible to return the result to a library such as Pako. If this would be possible, it may result in a stable and fast decompressing solution that costs just a few bytes instead of 22.6kb (pako_inflate.min.js).

**Comment by puzrin** [comment]
I think stackoverflow is better place to discuss this idea. I'm not experienced in browser programming.

**Comment by optimalisatie** [comment]
I understand. I've posted the question on stackoverflow. Thanks for the help!
