### ISSUE TITLE
[Question] Compatible with python 2.7 zlib

### ISSUE THREAD

**Issue by r4sas** [nodeca/pako#91]
> Надеюсь можно на русском =)

Совместим ли pako с реализацией zlib в python 2.7?
Я пытаюсь разобраться с такой проблемой:
Используется pako и [js-base64](https://github.com/dankogai/js-base64). Почему-то на выходе, после компрессии и преобразования в base64, получаются разные результаты.
```python
from base64 import b64encode, b64decode
from zlib import compress, decompress

t = bytes("Exception raised on compression and decompression errors.")
print compress(t.encode('utf-8'))
print b64encode(compress(t.encode('utf-8')))
```
Результат:
`eJxzrUhOLSjJzM9TKErMLE5NUQCykvNzC4pSi4tBool5KQopqcgiqUVF+UXFegB6IBXw`

```javascript
var text = "Exception raised on compression and decompression errors.";
console.log( Base64.encode( pako.deflate(text) ) );
```
Результат:
`eMKcc8KtSE4tKMOJw4zDj1MoSsOMLE5NUQDCssKSw7NzC8KKUsKLwotBwqLCiXkpCinCqcOIIsKpRUXDuUXDhXoAeiAVw7A=`

В какую сторону копать? Если проблема в js-base64, то подскажите пожалуйста лучшую реализацию оного.

**Comment by puzrin** [comment]
Sorry, can't help with python.

zlib does not depend on language. And this port produces binary equal results. I'd recommend to check if python's functions are wrapped or not http://nodeca.github.io/pako/#deflateRaw
