### ISSUE TITLE
Incorrect header check

### ISSUE THREAD

**Issue by GabrielGMartinsBr** [nodeca/pako#92]
In ruby i use this method to get the contents that i need:
`Zlib::Inflate.inflate(data);`

But when I try do the same in node.js with pako library
`pako.inflate(data)`

I get this error:
```
if (inflator.err) { throw inflator.msg || msg[inflator.err]; }
                      ^
incorrect header check
```

**Comment by puzrin** [comment]
Probably you need `inflateRaw` because your data is not wrapped. I'm not familiar with ruby.
