### ISSUE TITLE
Deflate my Data...

### ISSUE THREAD

**Issue by tschm2** [nodeca/pako#98]
Hello

Here is how i'm using pako:

      var data = "H4sIAAAAAAAEAK1UzW7....."
      var strData     = atob(b64Data);
      var charData    = strData.split('').map(function(x){return x.charCodeAt(0);});
      var binData     = new Uint8Array(charData);

      // Pako magic 
      var data        = pako.inflate(binData);
      let strData: string  = String.fromCharCode.apply(null, new Uint16Array(data));
      var parsedJson= JSON.parse(strData)

Can someone help me with the recreating of the data? I'm not able to get the var data = "H4sIAAAAA..." back... I'd be glad for a code snipped or something similar to be able to recreate the scenario.

What I tried:
pako.deflate(data) is not the same as binData

Thanks in advance

**Comment by puzrin** [comment]
I don't understand what you try to do. Have you seen code in example folder?

**Comment by tschm2** [comment]
Yes I've seen the code in the example folder.
Ok Sorry... i try to describe it again...

I read data  var data = "H4sIAAAAAAAEAK1UzW7....." from a QR-Code
Then i am able to get the JSON out of the data with the help of pako.
Now i changed the JSON and need to recreate the QR-Code.
Therefore i need to reverse all the steps above... 
And i'm not able to get the same result

**Comment by puzrin** [comment]
I don't know about QR. This library is just for inflate/deflate, well tested. Could you narrow down your question to this package only and provide executable code sample?

**Comment by puzrin** [comment]
`pako.deflate()` has many [compression options](http://nodeca.github.io/pako/#deflate). Your compressed source could have different ones.

**Comment by tschm2** [comment]
Ok Thanks a lot... I guess I made a mistake somewhere else... 
Pako seems to work fine :-) I'm sorry for the confusion

Thanks a lot for the fast replys!
