### ISSUE TITLE
Issue with utf-8 on deflate

### ISSUE THREAD

**Issue by kim1882** [nodeca/pako#99]
I'm trying to use pako to compress objects that might contain utf-8 characters.
For example,  {"foo":"bar","baz":"£€¥"} turns into: eJyrVkrLz1eyUkpKLFLSAZJVQPbiNUuVagFlsAhT
with:
```
function deflatePayload (data)
 {
   var charData = data.split('').map(function(x){return x.charCodeAt(0);});
   var binData = new Uint8Array(charData);
   var deflatePayload = pako.deflate(binData, { to: 'string' });
   deflatePayload = btoa(deflatePayload);
   return deflatePayload;
 }
```
Now, if I inflate back the previous result eJyrVkrLz1eyUkpKLFLSAZJVQPbiNUuVagFlsAhT turns into: {"foo":"bar","baz":"£¬¥"}
with:
```
function inflatePayload(data)
 {
   var strData = atob(data);
   var charData = strData.split('').map(function(x){return x.charCodeAt(0);});
   var binData = new Uint8Array(charData);
   try {
       var result = pako.inflate(binData);
       var strResult = String.fromCharCode.apply(null, new Uint16Array(result));
       return strResult;
   } catch (err) {
       console.log(err);
       return err;
   }
 }
```
So, my question is, Why can't I get the same input? How can I solve this?
Thanks in advance.

**Comment by puzrin** [comment]
Deflate needs binary 8-bit data. It doesn't know anything about encoding.

See https://github.com/nodeca/pako/tree/master/examples sources with comments.
